### ISSUE TITLE
[nri-bundle] kube-state-metrics.collectors removed by accident/on purpose?

### ISSUE THREAD

**Issue by seanfariacustomink** [newrelic/helm-charts#1022]
NRI-bundle helm chart has a section deleted by accident or was this on purpose?

Delete section during upgrade:
https://github.com/newrelic/helm-charts/commit/943d2f395d4206f9306eb8b0428c38392d2a6447#diff-775956f6065be7e353042b6388db8acb370f9684ce0ee04b2fdf089d435e85a9

Prometheus still supports these fields:

https://github.com/prometheus-community/helm-charts/blob/c3b697d31b8631fb8847f7f313155deeb5962f98/charts/kube-state-metrics/values.yaml#L250

Error when using collectors:
![image](https://user-images.githubusercontent.com/106612499/215848038-272ecfa9-8967-4995-a459-07272368187f.png)

All links referencing kube-state-metrics are also dead in the repo

i.e. https://github.com/kubernetes/kube-state-metrics/tree/master/charts/kube-state-metrics
![image](https://user-images.githubusercontent.com/106612499/215834257-c378bb8c-55f6-43cf-895a-9da26a31c102.png)

**Comment by seanfariacustomink** [comment]
I think I found the solution for collectors field syntax has been changed to the following:
# commuent out to disable
    collectors:
        # - certificatesigningrequests
        # - configmaps
        - cronjobs
        # - daemonsets
        - deployments
        # - endpoints
        - horizontalpodautoscalers
        # - ingresses
        - jobs
        # - leases
        # - limitranges
        # - mutatingwebhookconfigurations
        # - namespaces
        # - networkpolicies
        - nodes
        # - persistentvolumeclaims
        # - persistentvolumes
        # - poddisruptionbudgets
        - pods
        # - replicasets
        # - replicationcontrollers
        # - resourcequotas
        - secrets
        # - services
        # - statefulsets
        # - storageclasses
        # - validatingwebhookconfigurations
        # - volumeattachments

**Comment by paologallinaharbur** [comment]
yes exactly the nri-bundle is now shipped with the KSMv2 that changed the syntax for some of the values
