### ISSUE TITLE
[nri-statsd] Add global for NR license key secret

### ISSUE THREAD

**Issue by chauncey-garrett** [newrelic/helm-charts#1023]
The nri-bundle chart provides globals for storing a license key in a secret. I'd love to see the nri-statsd chart do the same.

<!DOCTYPE html>

global.customSecretLicenseKey | string | "" | Key in the Secret object where the license key is stored
-- | -- | -- | --
global.customSecretName | string | "" | Name of the Secret object where the license key is stored

**Comment by davidgit** [comment]
We appreciate you taking the time to bring this to our attention. After reviewing this issue, we are unable to commit on a timeline to resolution. When committing to resolve an issue, we take into account the type of issue, the customer impact, and the development effort required. If the situation changes, we will revisit this decision.

However, we encourage community contributions and are happy to collaborate on design proposals and pull requests. See our PR guidelines in the README. If you have any further questions or comments about this, please let us know by replying to this issue.
