### ISSUE TITLE
[nri-metadata-injection] Add Pod Disruption Budget when deploying more than one replica

### ISSUE THREAD

**Issue by mitchellmaler** [newrelic/helm-charts#104]
**Is your feature request related to a problem? Please describe.**

Currently the deployment does not come with a pod disruption budget.

**Describe the solution you'd like**

Add a pod disruption budget when deploying more than one replica to make sure at least one is always running.

**Comment by tyrken** [comment]
As a system webhook this really should have replicas default to more than 1 and a PDB as you suggest.  Glad to see there's already an affinity option, at least.

**Comment by kang-makes** [comment]
Issue moved to [newrelic/k8s-metadata-injection #173](https://github.com/newrelic/k8s-metadata-injection/issues/173) via [**ZenHub**](https://www.zenhub.com/)
