### ISSUE TITLE
[helm-charts] Issue #77 - Grep exclude not working to filter out logs

### ISSUE THREAD

**Issue by alpatekar** [newrelic/helm-charts#1044]
**Bug description**

Fluent bit Filter Grep Exclude not working for provided log message. The Regex provides no matches for keyword.

**Version of Helm and Kubernetes**

nri-bundle version 5.0.4

**Which chart?**

newrelic-logging

**What happened?**
When adding a grep exclude filter to filter out messages which contain the string *INFO*, the regex expression produces no matches. The log message is saved under the key "message".

log message:

"2023-03-08 16:01:30.969  INFO [ptesting,,] 1 --- [nio-8080-exec-5] LoggingFilter : Type: RESPONSE - http_method: GET - REMOVED - http_status: 200\n"

filter:
        [FILTER]
              Name      grep
              Match     *
              Exclude  message /INFO/

**What you expected to happen?**
Expected to remove all log records which have the string "INFO".

**Comment by thakerb** [comment]
See also: https://github.com/newrelic/helm-charts/issues/77

**Comment by luckslovez** [comment]
Same response as

**Comment by luckslovez** [comment]
Same as https://github.com/newrelic/helm-charts/issues/77#issuecomment-1625282702
Unless a custom parser is being used and thus the `message` field is assured to be present, there won't be such field. The default field is log. Using the following works fine;
```
[FILTER]
Name grep
Match *
Exclude log /INFO/
```

Please feel free to reopen if the issue persists.
