### ISSUE TITLE
[nri-bundle] global.tolerations not propagated to kube-state-metrics chart

### ISSUE THREAD

**Issue by daboom** [newrelic/helm-charts#1058]
**Bug description**
global.tolerations are not propagated to kube-state-metrics pod

**Version of Helm and Kubernetes**
Helm v3.10.0, Kubernetes v1.23.13

**Which chart?**
nri-bundle latest

**What happened?**
Set global.tolerations on nri-bundle chart values but kube-state-metrics pod didn't show them

**What you expected to happen?**
Set global.tolerations on nri-bundle chart values and see them in kube-state-metrics pod

**How to reproduce it?**
Set global.tolerations on nri-bundle chart

**Anything else we need to know?**

**Comment by thakerb** [comment]
@daboom any comments?

**Comment by daboom** [comment]
> @daboom any comments?
nope.
