### ISSUE TITLE
[nri-kubernetes] Update version of kube-state-metrics dependency

### ISSUE THREAD

**Issue by SashaShcherbyna** [newrelic/helm-charts#1076]
**Bug description**

Kubernetes: 1.26.2-gke.1000 
nri-bundle: 5.0.11 which includes kube-state-metrics: version 4.23.0. This cluster version has deprecated API **autoscaling.apiserver.k8s.io/v2beta2** looks like kube-state-metrics version 4.23.0 does not know about it, and generate lot of errors:
`E0504 14:57:41.765197 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.4/tools/cache/reflector.go:167: Failed to watch *v2beta2.HorizontalPodAutoscaler: failed to list *v2beta2.HorizontalPodAutoscaler: the server could not find the requested resource
86
W0504 14:58:12.635910 1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.4/tools/cache/reflector.go:167: failed to list *v2beta2.HorizontalPodAutoscaler: the server could not find the requested resource
85
E0504 14:58:12.635943 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.4/tools/cache/reflector.go:167: Failed to watch *v2beta2.HorizontalPodAutoscaler: failed to list *v2beta2.HorizontalPodAutoscaler: the server could not find the requested resource
84
W0504 14:59:04.231191 1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.4/tools/cache/reflector.go:167: failed to list *v2beta2.HorizontalPodAutoscaler: the server could not find the requested resource`

**Version of Helm and Kubernetes**
Helm: v3.9.3
Kubernetes: 1.26.2-gke.1000 (GCP GKE)

**Which chart?**

nri-bundle
version: 5.0.11

**What happened?**

We updated claster to version 1.26.2-gke.1000 and nri-bundle to version 5.0.11, after that i can see lot of errors in pod newrelic-kube-state-metrics
`W0504 14:40:45.760497 1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.4/tools/cache/reflector.go:167: failed to list *v2beta2.HorizontalPodAutoscaler: the server could not find the requested resource`

**What you expected to happen?**

Update to latest version newrelic-kube-state-metrics in nri-bundle

**How to reproduce it?**

GKE: 1.26.2 + nri-bundle: 5.0.11

**Comment by SashaShcherbyna** [comment]
version 5.0.15 includes kube-state-metrics: version 4.23.0.

**Comment by marinegreff** [comment]
Is there any update on this? Version 5.0.24 also includes kube-state-metrics:4.23.0 which forbids using nri-bundle on kubernetes 1.26

**Comment by davidgit** [comment]
hi @marinegreff, we are planning how to proceed with this upgrade because this upgrade requires deprecating support for older k8s versions.

We'll keep you posted

**Comment by marinegreff** [comment]
Hi @davidgit , thank you for the update. 

I understand the problem, but I just wanted to mention that older k8s versions are being deprecated quickly for cloud-managed clusters (1.23 is already deprecated, 1.24 is already deprecated for AKS and soon on GKE and EKS). We currently face the deprecation of k8s 1.25 by the end of this year, hence my question.
EOL dates for managed clusters:
- https://endoflife.date/google-kubernetes-engine
- https://endoflife.date/azure-kubernetes-service
- https://endoflife.date/amazon-eks

I'll keep an eye open

**Comment by davidgit** [comment]
Thanks @marinegreff! We are aware of it and that's one of the main reasons to de deprecate its support too

**Comment by davidgit** [comment]
Hi @catt231,

Our plan is to address this during the next couple of weeks.
