### ISSUE TITLE
[nri-bundle] <podsecuritypolicy apiversion : policy/v1beta1 is deprecated in k8s v.1.25+>

### ISSUE THREAD

**Issue by Narayanan-Balasubramanian** [newrelic/helm-charts#1117]
**Bug description**

**Version of Helm and Kubernetes**

The version of Helm and Kubernetes where the problem occurs.

**Which chart?**

The chart name and version.

**What happened?**

Described what happened, as detailed as possible and necessary.

**What you expected to happen?**

Please avoid saying "It should just work".

**How to reproduce it?**

Steps to reproduce the problem, as minimally and precisely as possible.

**Anything else we need to know?**

Surprise us!

**Comment by Narayanan-Balasubramanian** [comment]
In latest release for nri-bundle podsecurity.yaml template is using apiversion policy/v1beta1 which is not supported by kubernbetes 1.25+ version, could you please change it to the supported version. Thanks

**Comment by TravisDimmig-Intelex** [comment]
Is there a work-around, or an expected timeline for delivering a fix?

**Comment by Narayanan-Balasubramanian** [comment]
Hi, Please change the api-version in newrelic-logging podsecurity.yaml for the upgraded version of kubernetes

**Comment by davidgit** [comment]
Hi , 

If you are still experiencing issues, I would suggest to visit [New Relic Support](https://support.newrelic.com/), where you can engage the New Relic Support Community or open a support ticket depending on your support level. The support team is best positioned to assist with your specific needs. 

Please provide a link to this GitHub issue when submitting your community post or support ticket.

Thanks!
