### ISSUE TITLE
[newrelic-logging] 1.17.1 fails with parser 'cri,docker' is not registered

### ISSUE THREAD

**Issue by jimmyR** [newrelic/helm-charts#1131]
**Bug description**

using chart version 1.17.1 with the default config, we are getting this Parser error:

[2023/07/28 12:09:54] [error] [input:tail:tail.0] parser 'cri,docker' is not registered

**Version of Helm and Kubernetes**

Helm 3.12
k8s 1.25

**Which chart?**

newrelic-logging 1.17.1

**What happened?**

Throws an error about the Parser.  Previously the chart set LOG_PARSER to either cri or docker, but now sets it to cri,docker or docker,cri.

Seems the Parser can't handle a list?

**What you expected to happen?**

cri parsing works without throwing the error

**How to reproduce it?**

Install using the default configs

**Anything else we need to know?**

**Comment by bmcfeely** [comment]
@jimmyR this has been fixed in #1130. Apologies for the trouble! Please try again with the latest chart version (1.18.1), and let me know if you're still encountering a problem. Thanks!
