### ISSUE TITLE
[nri-bundle:5.0.22][newrelic-logging] logs sometimes are not shipped - no DNS resolution possible in newrelic-logging pods

### ISSUE THREAD

**Issue by immae1** [newrelic/helm-charts#1138]
**Bug description**

I see the following DNS issues inside the logging pods:
```log
[ warn] [net] getaddrinfo(host='kubernetes.default.svc.cluster.local', err=-3): Temporary failure in name resolution
[error] [filter:kubernetes:kubernetes.0] kubelet upstream connection error
```
And very often I see that the logs could not be transferred(' cannot be retried:) to my NewRelic instance:
```log

[ info] [input] pausing tail.0
level=info msg="Retryable error received. Will retry to send the logs (if there are attempts remaining, check Retry_Limit option)" error="Post \"https://log-api.newrelic.com/log/v1\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
[error] [engine] chunk '1-1690421202.xxxx.flb' cannot be retried: task_id=69, input=tail.0 > output=newrelic.0
```
If I exec into the running container of the logging pod, i see that the DNS resolution is somehow blocked/slow if e.g. do a `host -a github.com` etc. 

**Version of Helm and Kubernetes**

Helm v3.11.2  on k8s 1.26.3 

**Which chart?**

nri-bundle:5.0.22 / newrelic-logging

**What happened?**

No DNS resolution in logging pods, this might lead into retries for sending the logs. Sometimes the retry again fails and I assume that the logfile is not submitted completely

**What you expected to happen?**

DNS resolution inside the container should be possible. Logs should sent to NewRelic without timeouts/retries entirety. 

_**Possible Solution:**_
If I set hostnetwork = false by hand in the deamonset of the logging chart the errors disapear. I assume with this https://github.com/newrelic/helm-charts/pull/1100 the problems should be fixed. 

But I'm not 100% sure that setting `hostnetwork=false` is safe and that everything in the logging pod then will work as expected. 
Greetings

**Comment by bitva77** [comment]
I'm having this same issue and setting `hostNetwork: false` in the `newrelic-bundle-newrelic-logging` DaemonSet does fix it.  Not sure why it would under the host network anyway.

We are running in EKS and are using separate subnet (carrier grade) for our pod IP addresses.  I'm wondering if that's why coredns (kube-dns) is not available to pods running under the host network?

**Comment by 495315836713** [comment]
https://github.com/newrelic/helm-charts/pull/1207 <--- Updated logging chart to remove
https://github.com/newrelic/helm-charts/pull/1214 <--- Update nri-bundle

**Comment by juanjoarana** [comment]
`hostNetwork=true` has been removed in https://github.com/newrelic/helm-charts/pull/1207
