### ISSUE TITLE
[nri-bundle] noisy logs from `newrelic-bundle-nrk8s-kubelet-*`

### ISSUE THREAD

**Issue by darren-recentive** [newrelic/helm-charts#1143]
**Bug description**

After upgrading Helm Chart `nri-bundle` from `5.0.24` -> `5.0.25`, we get noisy logs
```
{
cluster_name:"<redact>"
container_name:"kubelet"
message:"time=\"2023-08-18T06:17:28Z\" level=warning msg=\"cpuLimitCores metric not available. using default max 96 cores\""
namespace_name:"newrelic"
newrelic.logPattern:"time=\"<DATETIME>\" level=warning msg=\"cpuLimitCores metric not available. using default max 96 cores\""
newrelic.source:"api.logs"
plugin.source:"k8s-fb-1.17.3"
pod_name:"newrelic-bundle-nrk8s-kubelet-"<redact>""
stream:"stderr"
timestamp:1692339448158
}
```
Noisy logs went way after downgrading the helm chart version on our clusters
![Screenshot 2023-08-17 at 11 19 53 PM](https://github.com/newrelic/helm-charts/assets/135057159/c02d0656-157d-446e-8c10-31fad0ae936e)

**Version of Helm and Kubernetes**

```
❯ helm version
version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}
```

Kubernetes `1.27` on  AWS EKS

**Which chart?**

nri-bundle, 5.0.25

**What happened?**

After upgrading the helm chart, we started seeing the logs.

**What you expected to happen?**

Not see the noisy logs

**How to reproduce it?**

Installed the chart on a new EKS cluster

**Anything else we need to know?**

https://forum.newrelic.com/s/hubtopic/aAX8W000000PGknWAG/warning-cpulimitcores-metric-not-available?t=1692339417333

**Comment by LHCGreg** [comment]
I created https://github.com/newrelic/nri-kubernetes/issues/854 in nri-kubernetes for the same problem around the same date as this issue.

**Comment by svetlanabrennan** [comment]
The fix was merged: https://github.com/newrelic/nri-kubernetes/pull/870

It will be in the next release.
