### ISSUE TITLE
nri-bundle ReleaseNotes ?

### ISSUE THREAD

**Issue by shaharr-ma** [newrelic/helm-charts#120]
I don't see any release-notes for nri-bundle, where i can find it ?

**Comment by paologallinaharbur** [comment]
Hello @shaharr-ma, thanks for the feedback, 
you are right currently release notes are not published.

I am checking with the team if we can have something in place to add them from now on.

**Comment by devurandom** [comment]
It seems this issue was resolved: Since a while most chart releases have release notes.

**Comment by paologallinaharbur** [comment]
Yes, we are currently adding release notes for `nri-infrastructure`, `nri-prometheus`, nri-bundle`, `nri-metadata-injection`, `nri-kube-events`.
They can be found directly in github under Releases

**Comment by devurandom** [comment]
> Yes, we are currently adding release notes for `nri-infrastructure`, `nri-prometheus`, `nri-bundle`, `nri-metadata-injection`, `nri-kube-events`.
> They can be found directly in github under Releases

This practice seems to have been abandoned recently. nri-bundle 2.1.0 and newer to do carry release notes anymore. Please reopen.

**Comment by paologallinaharbur** [comment]
Release notes have been updated, I will keep this issue open till the process get automatised.

Thanks again for bringing this up!

**Comment by devurandom** [comment]
The issue persists. Is there something one could help with to get this automated?

**Comment by paologallinaharbur** [comment]
I updated the release notes, we have been thinking how to incorporate a proper way to do so in the CI/CD making use of the commit messages. 

However it is not in place yet and we have to rely on us to update each release manually. Feel free to contribute if you have any idea regarding how to solve this annoying issue
