### ISSUE TITLE
[ri-bundle] how to input newrelic license key to value.yaml

### ISSUE THREAD

**Issue by yoshuhire** [newrelic/helm-charts#1229]
### Description
I have decided to use nri-bundle to install new relic agent to kubernetes.
I would like to use helm-chart named "nri-bundle" which is in public and only define "values.yaml".

### Questions
Is it possible to refer to the kubernetes secret for the license key?
If it is, please tell me how?

### Reference
https://github.com/newrelic/helm-charts/blob/master/charts/nri-bundle/Chart.yaml

**Comment by mangulonr** [comment]
Hi 

In this link you will find our documentation where is explained how to reference the license key from a secret.
https://github.com/newrelic/helm-charts/tree/master/charts/nri-bundle

Check customSecretLicenseKey and  customSecretName keys.
