### ISSUE TITLE
[php-daemon]: There is no php-daemon Helm Chart

### ISSUE THREAD

**Issue by damienwebdev** [newrelic/helm-charts#127]
As a developer, I'd like to be able to deloy the New Relic PHP-Daemon as a chart with vendor-specific infrastructure configuration handled by New Relic.

**Is your feature request related to a problem? Please describe.**

I don't really want to maintain my own custom deployment of the PHP-Daemon.

**Describe the solution you'd like**

I'd much prefer a simple chart install.

**Describe alternatives you've considered**

Obviously, running my own Helm Chart, or creating my own deployment, but I'd rather not.

**Comment by roobre** [comment]
Hi there,

For the time being we are not comfortable with incorporating a chart into our repo for the PHP agent, as it could be read as an official or recommended way of deploying the PHP agent. We believe users should do this on their side, as it would heavily depend on how they are architecting their applications.
