### ISSUE TITLE
[synthetic-job-manager] container not running on arm64

### ISSUE THREAD

**Issue by pragmaticivan** [newrelic/helm-charts#1488]
**Bug description**

This project doesn't seem to support/work with arm64

**Which chart?**

latest

**What happened?**
The container can't start on arm64 nodes.

**How to reproduce it?**
Run project on arm64 nodes

**Comment by pragmaticivan** [comment]
Could someone at least share why?

**Comment by bpeckNR** [comment]
Chrome, which we use as part of the browser runtime with Job Manager, does not provide an ARM based Linux install. We do not want to change to use Chromium instead. This blocks our ability to support ARM with Job Manager and its runtimes.
