### ISSUE TITLE
[nri-bundle] Can't find the release 1.8.0

### ISSUE THREAD

**Issue by ahmad-hamade** [newrelic/helm-charts#150]
**Bug description**

Running helm repo add, refresh and find returning only 1.7.2 where 1.8.0 is the latest version

**Which chart?**

newrelic/nri-bundle

**Comment by paologallinaharbur** [comment]
Hello @ahmad-hamade I am currently looking into it

**Comment by paologallinaharbur** [comment]
We had an issue with the release pipeline, 1.9.0 is now live @ahmad-hamade Thanks for reporting!
