### ISSUE TITLE
Please respect fullnameOverride like all the other helm charts

### ISSUE THREAD

**Issue by DTTerastar** [newrelic/helm-charts#160]
**Bug description**

Please respect fullnameOverride like all the other helm charts

**Version of Helm and Kubernetes**

n/a

**Which chart?**

nr-bundle and all subcharts

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
