### ISSUE TITLE
[nri-metadata-injection] DigitalOcean Kubernetes: Mutating webhook with a TimeoutSeconds value greater than 29 seconds will block upgrades

### ISSUE THREAD

**Issue by devurandom** [newrelic/helm-charts#175]
**Bug description**

Managed DigitalOcean Kubernetes clusters cannot update automatically as long as New Relic instrumentation is installed.

**Version of Helm and Kubernetes**

I am using Terraform 0.13.5 with hashicorp/helm 1.3.2 ran against Kubernetes 1.18.10-do.1.

**Which chart?**

nri-bundle version 1.9.1.

**What happened?**

Trying to update my Kubernetes cluster on DigitalOcean using their UI, I see following messages:
* [Mutating webhook with a TimeoutSeconds value greater than 29 seconds will block upgrades](https://www.digitalocean.com/docs/kubernetes/resources/clusterlint-errors#admission-controller-webhook-timeout)
* [Mutating webhook is configured in such a way that it may be problematic during upgrades](https://www.digitalocean.com/docs/kubernetes/resources/clusterlint-errors#admission-controller-webhook-replacement)

These block automatic upgrades. Sadly the links to the documentation lead into the void - their targets do not exist.

**What you expected to happen?**

The DigitalOcean Kubernetes linter (integrated into their web UI) should not report anything and automatic upgrades of DigitalOcean Kubernetes clusters should just work without user intervention.

**How to reproduce it?**

1. Create a DigitalOcean Kubernetes cluster at version 1.18.10-do.1.
2. Install nri-bundle 1.9.1 using Helm.
3. Try to upgrade the Kubernetes cluster to version 1.19.3-do.1.

**Comment by devurandom** [comment]
I tried setting `nri-metadata-injection.timeoutSeconds` to `10` myself in Terraform, but that does not seem to have an effect on `mutatingwebhookconfigurations/newrelic-infrastructure-nri-metadata-injection`, which is still at `30`, which I believe is the default.

**Comment by devurandom** [comment]
> I tried setting `nri-metadata-injection.timeoutSeconds` to `10` myself in Terraform, but that does not seem to have an effect on `mutatingwebhookconfigurations/newrelic-infrastructure-nri-metadata-injection`, which is still at `30`, which I believe is the default.

Setting this to 10 seems to work now, with nri-bundle 2.0.0, but the default is still at 30s, which causes DigitalOcean's Kubernetes linter to complain for the reasons mentioned in https://www.digitalocean.com/docs/kubernetes/resources/clusterlint-errors#admission-controller-webhook-timeout.

**Comment by paologallinaharbur** [comment]
Yes, since:
```
name: nri-metadata-injection
version: 1.1.1
```
such parameter can be configured https://github.com/newrelic/helm-charts/pull/129/files

We would prefer not to change the default value in order to avoid any possible breaking change as specified in the PR
