### ISSUE TITLE
[newrelic-logging] Outdated Fluent Bit version

### ISSUE THREAD

**Issue by pdefreitas** [newrelic/helm-charts#179]
**Is your feature request related to a problem? Please describe.**

Current latest version of the helm chart is still running on Fluent Bit v1.0.3, which lacks a lot of new features such as [multiline support in Docker_mode](https://github.com/fluent/fluent-bit/pull/2043).

**Describe the solution you'd like**

Bump Fluent Bit version to a higher version and keep the dependency updated overtime to ensure compatibility.

**Describe alternatives you've considered**

Running my own image.

**Additional context**

https://docs.fluentbit.io/manual/pipeline/inputs/tail#docker_mode

**Comment by jsubirat** [comment]
Addressed in [this PR](https://github.com/newrelic/helm-charts/pull/165)
