### ISSUE TITLE
[nri-kube-events] Missing podAnnotations value

### ISSUE THREAD

**Issue by benjick** [newrelic/helm-charts#194]
Hello.

I would like to be able to set `podAnnotations` for the chart `nri-kube-events` so I can add the annotation `"cluster-autoscaler.kubernetes.io/safe-to-evict": "true"`. Currently `emptyDir: {}` is blocking **Kubernetes Cluster Autoscaler** from rescheduling the pods.

**Describe the solution you'd like**

I would like to be able to set the value `podAnnotations`

**Additional context**

Cluster Autoscaler log:
```
Fast evaluation: node xxx.compute.internal cannot be removed: pod with local storage present: new-relic-nri-kube-events-76cc55f5f6-crt6c
```

**Comment by kang-makes** [comment]
We appreciate you taking the time to bring this to our attention. After reviewing this issue, we are unable to commit on a timeline to resolution. When committing to resolve an issue, we take into account the type of issue, the customer impact, and the development effort required. If the situation changes, we will revisit this decision.

If you need information about to contribute to fix this issue, I left an explanation here: https://github.com/newrelic/helm-charts/pull/794#issuecomment-1118795491

We encourage community contributions and are happy to collaborate on design proposals and pull requests. See our PR guidelines in the README. If you have any further questions or comments about this, please let us know by replying to this issue.
