### ISSUE TITLE
newrelic-infrastructure: needs affinity values

### ISSUE THREAD

**Issue by cweidinger** [newrelic/helm-charts#210]
add .Values.affinity to the Daemonset's spec.template.spec.affinity

**Is your feature request related to a problem? Please describe.**

We need to prevent this from getting deployed to fargate on eks and the most sane way is an affinity rule to avoid fargate's lavel

**Describe the solution you'd like**
Add

{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
to the Daemonset's template like
https://github.com/helm/charts/blob/90590531b829dbc1142833a5d124cef7cc17b893/stable/prometheus-node-exporter/templates/daemonset.yaml#L80

**Describe alternatives you've considered**

We considered adding a standard label to all our nodes which wouldn't be applied to the fargate instance which we could use with the newrelic-infrastructure's nodeSelector but that would require a redeploy of all of our clusters and doesn't make much sense to have a node label that applies to all nodes (except fargate)

**Comment by freehck-codefresh** [comment]
We need this functionality too. We use newrelic to monitor only specific pods, and we do know their location. It's kind of overhead to deploy the daemonset on all the nodes.

**Comment by DragonStuff** [comment]
We at [TableCheck Japan](https://tablecheck.com/) use the newrelic-infrastructure chart extensively, and want to expand our usage to our mixed AWS EKS Managed Node Groups & Fargate cluster.

Please let me know if you want me to open a new MR and sign the CLA (as I see this is unsigned @freehck-codefresh).

**Comment by roobre** [comment]
H there!
Thanks for raising your concerns. Jut wanted to let you know that we're working on EKS fargate support now. As a part of this effort, we're also adding the ability to add custom `nodeAffinity` items to the daemonSet :)

**Comment by roobre** [comment]
This feature was implemented in #348. Definiing `global.fargate` will now automatically add affinity rules to exclude the DaemonSet from fargate nodes.

in the future, this label will also enable other features for instrumenting EKS fargate, in which we're still working.

Additionally, this PR also allwos to manually define node affinity rules. However please keep in mind that if these rules are manually overriden, `global.fargate` will no longer add the fargate exclusion automatically.

**Comment by DragonStuff** [comment]
@roobre Thank you so much, we’re going to use this immediately. Keep up the great work and we 💜 New Relic.
