### ISSUE TITLE
[nri-bundle] Windows 2004 Build Support

### ISSUE THREAD

**Issue by andrewpurdin** [newrelic/helm-charts#244]
**Is your feature request related to a problem? Please describe.**
We are unable to deploy the new relic infrastructure bundle on Windows nodes running the 2004 version.

**Describe the solution you'd like**

We would like to be able to reference a version of the chart that works with Windows 2004. 

**Describe alternatives you've considered**

N/A

**Additional context**

It seems the current version is built with 1809 (which works on our 1909 nodes), but 1809 is not compatible with 2004.

**Comment by paologallinaharbur** [comment]
Hello, the windows 2004 image has been just released: 
 - https://hub.docker.com/layers/newrelic/infrastructure-k8s/2.2.0-windows-2004-alpha/images/sha256-f04611b7f5c66a96a7047d37bd462acd0734480c93f0c2a456ea785c72d187ac?context=explore

Notice as well that the chart has been updated to support multiple Windows version node in the same cluster:

   - **Feat** support multiple Windows builds in same cluster (https://github.com/newrelic/helm-charts/pull/286)
  
      The alfa Windows support has been improved in order to be compatible with cluster having Windows nodes running different version and build of the OS.
      
      A new DaemonSet will be created for each build version specified and ti will be assigned only to the node being labeled for that specific build.
      
      The following behaviour is controlled by the following values
      ```yaml
      windowsOsList:
        - version: 2004
          imageTag: 2.2.0-windows-2004-alpha
          buildNumber: 10.0.19041
      ```
      
      Moreover the `Image. windowsTag` property has been deprecated

**Comment by paologallinaharbur** [comment]
![Uploading Screen Shot 2021-02-25 at 10.16.05 AM.png…]()
