### ISSUE TITLE
[nri-metadata-injection] UPGRADE FAILED: cannot patch "newrelic-bundle-nri-metadata-injection-job" with kind Job

### ISSUE THREAD

**Issue by DTTerastar** [newrelic/helm-charts#248]
**Bug description**

This chart when it updates the job version number attempts to update the job which kubernetes doesn't allow a Job's spec to be overwritten so we get this error:

UPGRADE FAILED: cannot patch "newrelic-bundle-nri-metadata-injection-job" with kind Job: Job.batch "newrelic-bundle-nri-metadata-injection-job" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"app.kubernetes.io/instance":"newrelic-bundle", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"nri-metadata-injection", "app.kubernetes.io/version":"1.3.1", "controller-uid":"12eb587d-eb66-4eba-a576-554bf3116b30", "helm.sh/chart":"nri-metadata-injection-1.3.1", "job-name":"newrelic-bundle-nri-metadata-injection-job"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume(nil), InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"nri-metadata-injection-job", Image:"newrelic/k8s-webhook-cert-manager:1.3.1", Command:[]string{"./generate_certificate.sh"}, Args:[]string{"--service", "newrelic-bundle-nri-metadata-injection", "--webhook", "newrelic-bundle-nri-metadata-injection", "--secret", "newrelic-bundle-nri-metadata-injection", "--namespace", "kube-system"}, WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount(nil), VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), StartupProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]core.EphemeralContainer(nil), RestartPolicy:"Never", TerminationGracePeriodSeconds:(*int64)(0xc013cca9b0), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"newrelic-bundle-nri-metadata-injection", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc0121c4c80), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), PreemptionPolicy:(*core.PreemptionPolicy)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), Overhead:core.ResourceList(nil), EnableServiceLinks:(*bool)(nil), TopologySpreadConstraints:[]core.TopologySpreadConstraint(nil)}}: field is immutable

**Version of Helm and Kubernetes**

helm 3.4.2
kubernetes 1.18 (eks)

**Which chart?**

nri-metadata-injection via nri-bundle 
2.1.1

**What happened?**

Ran helm upgrade (via helmfile):

 PATH:
      Z:\Build\Work\7ec7c37239a99c76\kubernetes\tools\helm\3.4.2\helm.exe

    ARGS:
      0: helm (4 bytes)
      1: upgrade (7 bytes)
      2: --install (9 bytes)
      3: --reset-values (14 bytes)
      4: newrelic-bundle (15 bytes)
      5: newrelic/nri-bundle (19 bytes)
      6: --wait (6 bytes)
      7: --create-namespace (18 bytes)
      8: --namespace (11 bytes)
      9: kube-system (11 bytes)
      10: --values (8 bytes)
      11: Z:\Build\Temp\buildTmp\values617232677 (38 bytes)
      12: --history-max (13 bytes)
      13: 10 (2 bytes)

**What you expected to happen?**

Expected the chart to be updated and for no errors to stop our ci/cd process.

**How to reproduce it?**

Install via helm with one chart version, install the next point release and it should happen.  If you rerun it, it may succeed (basically it just fails once).

**Anything else we need to know?**

Surprise us!

**Comment by erkannt** [comment]
We use `helm-operator` and flux. To get an upgrade to work I always have to:

1. `helm rollback` to previous release
2. `kubectl delete job` the `nri-metadata-injection-job`
3. wait for `helm-operator` to retry

Would be nice if this wouldn't be necessary.

Maybe cleaning up the successful job upon completion can solve this issue.
https://kubernetes.io/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically

**Comment by DTTerastar** [comment]
An easy fix would be to name the job with the image tag appended
