### ISSUE TITLE
[newrelic-infrastructure] Do not grant permission to "secret" if control plane monitoring is not configured

### ISSUE THREAD

**Issue by roobre** [newrelic/helm-charts#282]
The default RBAC role for the cluster grants access to read secrets in other namespaces. This is done to allow the integration to fetch the mTLS secrets for etcd, which are in turn required to gather metrics from it.

However this permission can be viewed as unnecessary, specially if control plane monitoring is not configured.

**Describe the solution you'd like**

It would be good if the helm chart skipped this permission if control plane monitoring is not configured for the cluster (e.g. `etcdTlsSecretName` is not defined).

**Describe alternatives you've considered**

The default rbac config can be ommited completely by setting `rbac.create` to false. However this requires the user to manually create an rbac with all the other requirements for the integration to work.

**Comment by roobre** [comment]
Additionally, it would be good if the current role could be limited to access just the namespace where the control plane resides. I think we could specify something in the values.yml for this, like `etcdNamespace` defaulting to blank, in which case the role would be unbound as it is now.

**Comment by paologallinaharbur** [comment]
the idea is to create a rolebinding for the secrets instead of the clusterrolebinding granting access to the newrelic namespace and the etcd one
