### ISSUE TITLE
[nri-bundle] global variable to pull from private repository

### ISSUE THREAD

**Issue by panho66** [newrelic/helm-charts#287]
**A single global variable to pull images from private repository rather than docker hub due to issue**

toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

e.g. global.repos=nexus3.abc.com/air-gap
       expect to pull image from nexus3.abc.com/air-gap/newrelic/infrastructure-k8s:1.2

It makes easy to overwrite each images e.g.

--set newrelic-infrastructure.image.repository=nexus3.abc.com/air-gap/newrelic/infrastructure-k8s  \
--set newrelic-logging.image.repository=nexus3.abc.com/air-gap/newrelic/newrelic-fluentbit-output  \
--set nri-kube-events.image.kubeEvents.repository=nexus3.abc.com/air-gap/newrelic/nri-kube-events   \
--set nri-kube-events.image.infraAgent.repository=nexus3.abc.com/air-gap/newrelic/k8s-events-forwarder  \
--set nri-metadata-injection.image.repository=nexus3.abc.com/air-gap/newrelic/k8s-metadata-injection   \
--set nri-metadata-injection.jobImage.repository=nexus3.abc.com/air-gap/newrelic/k8s-webhook-cert-manager  \

**Comment by AlbertoPeon** [comment]
We are facing the same issue ourselves!

**Comment by kang-makes** [comment]
It took time but here you have it: https://github.com/newrelic/helm-charts/tree/master/library/common-library#values-managed-globally
