### ISSUE TITLE
[newrelic-infrastructure] Exposing configuration settings to helm chart

### ISSUE THREAD

**Issue by alexangas** [newrelic/helm-charts#296]
**Is your feature request related to a problem? Please describe.**

I would like to easily configure additional [infrastructure agent configuration settings](https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings/) via the helm chart. Some have already been added such as https://github.com/newrelic/helm-charts/issues/141. Personally I'm looking for those related to sampling, but others may also be useful.

**Describe the solution you'd like**

Environment variables `NRIA_METRICS_NETWORK_SAMPLE_RATE`, `NRIA_METRICS_PROCESS_SAMPLE_RATE`, `NRIA_METRICS_STORAGE_SAMPLE_RATE`, `NRIA_METRICS_SYSTEM_SAMPLE_RATE` added to the env section of the daemonset templates for Linux and Windows, and exposed as values.

**Describe alternatives you've considered**

Forking the chart or using a post renderer such as kustomize.

**Additional context**

N/A

**Comment by roobre** [comment]
Hi,

Thanks for raising this concern, as well as taking the time to write the linked PR.

Given the [high number of settings](https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings/#agent-variables) that can be configured for the infrastructure agent and integrations, we are trying to move away of aliasing all possible env vars to the chart as Values. The ones we currently have are there for legacy or backwards-compatibility reasons.

Changing this (and any other) setting should be possible using the [`config` key](https://github.com/newrelic/helm-charts/blob/1af7ebd4f88bbdb466d7585878d71dcc10478221/charts/newrelic-infrastructure/values.yaml#L141), which is expanded and mounted as a config file for the infrastructure agent. Could you please try it and see if it works for you?

**Comment by alexangas** [comment]
@roobre Not wanting to alias all of the possible env vars makes total sense, and is definitely something that I considered at the time but didn't realise the better way. This is my first attempt at New Relic but I think your comment has helped me understand a lot! It looks like for the config key, the relevant parameters from https://github.com/newrelic/infrastructure-agent/blob/master/assets/examples/infrastructure/newrelic-infra-template.yml.example can be included. It should even be possible to use the nri-bundle chart and pass them through from there. Is that correct?

**Comment by roobre** [comment]
Yes, that is totally correct. Just keep in mind that you'll have to "nest" the value under the `infrastructure-bundle` key. just like this example:

https://github.com/newrelic/helm-charts/blob/2aae7be7dad949d986a5b0fd265b803d908db328/charts/nri-bundle/values.yaml#L52-L54

**Comment by alexangas** [comment]
Great, I tested this and verified the file was created correctly on the container. Thanks for your help!
