### ISSUE TITLE
[newrelic-logging] Add field in chart to allow for unique cluster id faceting

### ISSUE THREAD

**Issue by leowmjw** [newrelic/helm-charts#298]
**Describe *in detail* the feature/behavior/change you'd like to see.**

Our workload can be in multiple clusters at any one time.  Current cluster field is used to broadly facet to staging or production workloads.
Want to have an additional field in the helm value to allow us to facet based on a **cluster-unique-id**

**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Allow to additional field in the values file; maybe call it **cluster-unique-id** e.g. eks-prod-cluster-west2, eks-prod-cluster-east1

This field must be easily faceted by the users in addition to the cluster field; which is used to differentiate staging/production e.g. k8s-production, k8s-development

Example Query: "cluster:k8s-production cluster-unique-id:eks-prod-cluster-west2 error"

**Describe alternatives you've considered**

We can use the existing cluster field to indicate the actual cluster identifier e.g eks-prod-cluster-east1 but it will have problems when trying to search for workloads that move among clusters or can have multiple copies in multiple clusters.
We should not put the burden on the developers to need to know which clusters the workloads are in.

**Additional context**

This additional field allows developers to see their workload only having problems in certain clusters and they can trigger an evacuation of their workload from that cluster into another that is operational, and monitor

**Comment by jsubirat** [comment]
I'm closing this issue in favour of #75, which should cover this use case as well.

**Comment by jsubirat** [comment]
Nevertheless, please take into account that it is currently possible to achieve what you were requesting, as now the full Fluent Bit configuration is editable via `values.yml`: https://github.com/newrelic/helm-charts/blob/master/charts/newrelic-logging/values.yaml#L49-L137

So, you could just use the following for your use case:

fluentBit:
    config:
        filters: |
      [FILTER]
          Name                kubernetes
          Match               kube.*
          # We need the full DNS suffix as Windows only supports resolving names with this suffix
          # See: https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#dns-limitations
          Kube_URL            https://kubernetes.default.svc.cluster.local:443
          Buffer_Size         ${K8S_BUFFER_SIZE}
          K8S-Logging.Exclude ${K8S_LOGGING_EXCLUDE}
      [FILTER]
          Name           record_modifier
          Match          *
          Record         cluster_name ${CLUSTER_NAME}
      [FILTER]
          Name record_modifier
          Match *
          Record cluster_name ${CLUSTER_NAME}
          Record cloud aws
          Record cloud_region ap-southeast-2

Bear in mind that you currently need to include the existing filters as well as you own. When we merge this other PR #609, we'll be able to specify just the extra ones instead of rewriting them all.
