### ISSUE TITLE
[nri-metadata-injection] Cert manager Documentation

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/helm-charts#302]
**Is your feature request related to a problem? Please describe.**

We merged already a feature to support the certificate manager, however this is not well documented. 
https://github.com/newrelic/helm-charts/pull/173

**Describe the solution you'd like**

We should properly document this feature and decide if it is possible (avoiding any breaking change) to make it the default configuration

**Comment by paologallinaharbur** [comment]
The main issue is that we cannot know if the user has already installed the cert-manager or not. 

We could add it as a dependency as we do for KSM, but I am not sure it would be recommended

**Comment by kang-makes** [comment]
Issue moved to [newrelic/k8s-metadata-injection #174](https://github.com/newrelic/k8s-metadata-injection/issues/174) via [**ZenHub**](https://www.zenhub.com/)
