### ISSUE TITLE
[newrelic-infrastructure] document how to use integrations_config to configure integrations

### ISSUE THREAD

**Issue by roobre** [newrelic/helm-charts#322]
The newrelic-infrastructure chart supports mounting integration config files through the use of the `integrations_config` key. However, this is not very well documented neither in the readme, nor in the docs. Futhermore, the default value of `{}` might hint users to mistakenly believe it is an object, while in fact it is an array.

A simple example on how to use it should be added to the `values.yml` file, commented out, and the placeholder should be `[]`:

```yaml
# Define integration configurations for monitoring services inside the cluster
integrations_config: []
#integrations_config:
#  - name: nri-example.yml
#    data:
#      integration_name: com.newrelic.example
#      instances:
#        - name: nri-example
#          command: metrics
```

**Comment by paologallinaharbur** [comment]
In infrastructure chart v3 it is an object and it has been documented properly [here](https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/monitor-services/monitor-services-running-kubernetes) and in values
