### ISSUE TITLE
[nri-metadata-injection] missing podAnnotation for k8s-metadata-injection Job

### ISSUE THREAD

**Issue by ghost** [newrelic/helm-charts#323]
Describe *in detail* the feature/behavior/change you'd like to see.

I would like to be able to set `podAnnotations` for the **job** on the chart `nri-metadata-injection` so I can add the annotation "consul.hashicorp.com/connect-inject": "false". The job runs infinitely as the envoy sidecar and consul sidecar processes don't end when the job runs to completion. 

If I was able to set pod annotations on the job I would be able to disable the sidecar injection and have the job run to completion.

**Is your feature request related to a problem? Please describe.**

Users who enable sidecar injection by default won't be able to kill the injection job, as the envoy proxy process doesn't end when the job finishes, and the pod stays running. 

Currently `podAnnotations` are enabled for the deployment. I don't see any reason why they wouldn't also be enabled for the job.

**Comment by kang-makes** [comment]
We appreciate you taking the time to bring this to our attention. After reviewing this issue, we are unable to commit on a timeline to resolution. When committing to resolve an issue, we take into account the type of issue, the customer impact, and the development effort required. If the situation changes, we will revisit this decision.

If you need information about how to contribute to fixing this issue, I left an explanation here: https://github.com/newrelic/helm-charts/pull/794#issuecomment-1118795491

We encourage community contributions and are happy to collaborate on design proposals and pull requests. See our PR guidelines in the README. If you have any further questions or comments about this, please let us know by replying to this issue.
