### ISSUE TITLE
[nri-metadata-injection] Don't run as root

### ISSUE THREAD

**Issue by invidian** [newrelic/helm-charts#337]
**Is your feature request related to a problem? Please describe.**

Currently `nri-metadata-injection` Deployments runs as root, which is not really needed.

**Describe the solution you'd like**

`nri-metadata-injection` runs as non-root user.

**Additional context**

This might break thing if one runs it on different port. See https://github.com/newrelic/k8s-metadata-injection/issues/69 for more details.

**Comment by kang-makes** [comment]
Issue moved to [newrelic/k8s-metadata-injection #175](https://github.com/newrelic/k8s-metadata-injection/issues/175) via [**ZenHub**](https://www.zenhub.com/)
