### ISSUE TITLE
[nri-statsd] Consider using Secret instead of ConfigMap

### ISSUE THREAD

**Issue by gmelillo** [newrelic/helm-charts#373]
**Is your feature request related to a problem? Please describe.**

At the moment the configuration is stored inside a ConfigMap and during `helm diff` secrets get displayed in cleartext.

**Describe the solution you'd like**

Will be nice to have the config file inside a secret. That way it will be possible to filter out this item from the diff with the flag `--suppress-secrets`

**Additional context**

I'd like to submit a PR to address this issue if it is something you will be interested in.

**Comment by gmelillo** [comment]
@paologallinaharbur  @dbrota @gsanchezgavier @roobre We do have something already working on an internal fork, if it is ok I'll propose a PR to discuss if the implementation is ok

**Comment by roobre** [comment]
Hi @gmelillo, thanks for raising this. The `CODEOWNERS` file is not entirely up to date regarding this chart, and this should (if I'm not mistaken) be maintained by @newrelic/caos. They'll get back to you as soon as they can :)

**Comment by varas** [comment]
Hey @gmelillo of course, if could submit a PR that'd be awesome, thanks!

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
