### ISSUE TITLE
Use helm-docs for generating charts documentation

### ISSUE THREAD

**Issue by invidian** [newrelic/helm-charts#397]
It's easy for README.md files of charts to get out of date, so perhaps tool like https://github.com/norwoodj/helm-docs could be used to update them automatically?

**Comment by kang-makes** [comment]
[All](https://github.com/newrelic/newrelic-k8s-metrics-adapter/blob/main/charts/newrelic-k8s-metrics-adapter/README.md.gotmpl) [of](https://github.com/newrelic/nri-kubernetes/blob/main/charts/newrelic-infrastructure/README.md.gotmpl) [the](https://github.com/newrelic/nri-prometheus/blob/main/charts/nri-prometheus/README.md.gotmpl) [helm](https://github.com/newrelic/k8s-metadata-injection/blob/main/charts/nri-metadata-injection/README.md.gotmpl) [charts](https://github.com/newrelic/nri-kube-events/blob/main/charts/nri-kube-events/README.md.gotmpl) that we deprecated on #795 has the README generated automatically 🎉 

(Except infra-operator but we have a task for that: newrelic/newrelic-infra-operator#145
