### ISSUE TITLE
Rewrite chart-bump-action

### ISSUE THREAD

**Issue by roobre** [newrelic/helm-charts#404]
**Is your feature request related to a problem? Please describe.**

Our current solution for automatically bumping charts is a custom action written in Node. This action is hard to maintain and very often gets security warnings, given the high number of dependencies.

Additionally, since this workflow also uses a third party action for creating pull requests, we cannot supply it a custom token to allow it to run CI checks due to security concerns.

**Describe the solution you'd like**

It would be great to rewrite the chart-bump action in go, and automate PR creation with the `gh` tool rather than a third-party action.

**Comment by kang-makes** [comment]
This is now done by the renovate bot.
