### ISSUE TITLE
newrelic-infrastructure Windows support

### ISSUE THREAD

**Issue by mr-smithers-excellent** [newrelic/helm-charts#41]
**Is your feature request related to a problem? Please describe.**

Currently the `newrelic-infrastructure` Helm chart can only be run on Linux nodes. With the introduction of Windows nodes in EKS & GKE, it would be nice to have a version of this chart that can be run on Windows nodes. I see a version of the Docker `newrelic/infrastructure-k8s` image is now available with [windows-1909](https://hub.docker.com/layers/newrelic/infrastructure-k8s/1.21.0-windows-1909-alpha/images/sha256-3aee9ca7b4a7a28af87b9ee32f428933c1f9db875b72543b0bc8b157b3b383f6?context=explore) and [windows-1809](https://hub.docker.com/layers/newrelic/infrastructure-k8s/1.21.0-windows-1809-alpha/images/sha256-b56527942ac1bc1e5b4f517d92f6dcc613922502f05607e43c23a850a0f2d16e?context=explore) variants (in alpha).

**Describe the solution you'd like**

A version of the `newrelic-infrastructure` Helm chart that can be run on Windows nodes.

**Describe alternatives you've considered**

I've gone down the path of patching the existing chart with Windows alternatives - ripping out things like `hostNetwork`, which is currently not supported in Windows. In my mind, there should really be an official New Relic version though.

**Additional context**

New Relic Kubernetes integration is a `helm install` command away for Linux nodes, but not quite as straight and forward for Windows.

**Comment by alejandrodnm** [comment]
Hi @mr-smithers-excellent as you said the Windows support is still in alpha, we have plans to add support for it on the helm chart when we start getting closer to GA, of course, PRs are always welcome :)

We'll keep this ticket open and keep it up to date. Thanks.

**Comment by mr-smithers-excellent** [comment]
@alejandrodnm I believe I have this working using plain old `.yaml` config and would be happy to contribute. From a design perspective, I expect this would entail adding a 2nd Windows-specific `DaemonSet` that would be controlled via some new flag value (eg `enableWindows`). Let me know if you have a different opinion though.

**Comment by alejandrodnm** [comment]
@mr-smithers-excellent yes we will need a Windows-specific `Daemonset` you can try replicating what we have here http://download.newrelic.com/infrastructure_agent/integrations/kubernetes/newrelic-infrastructure-k8s-linux-windows1809-1.21.0-alpha.yaml

Both `Daemonsets` share the same service account, cluster name, license key, etc.

let's add `enableWindows: false` and `enableLinux: true` to the values, and make the Linux Daemonset also configurable but enable by default. 

For the docs I was thinking to add clear information on the supported versions and how to identify what version your nodes support. Something like:

> To check your Windows version:
>
>   - Open a command window.
>   - Run the following command:

```
Reg Query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /v ReleaseIdcmd.exe
```

> Example: Get Windows version (the node's running 1809) from a BusyBox container.

```
$ kubectl exec -it busybox1-766bb4d6cc-rmsnj -- Reg Query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /v ReleaseId

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion
	ReleaseId	REG_SZ	1809
```

What do you think? I can help with the docs part if you want.

**Comment by mr-smithers-excellent** [comment]
@alejandrodnm sounds good, should be able to take a crack at this tomorrow.
