### ISSUE TITLE
[newrelic-infrastructure] Enable configuring updateStrategy better for the daemonset

### ISSUE THREAD

**Issue by gdziwoki** [newrelic/helm-charts#410]
In big environments rolling update of the daemonset will be fery slow.
It would be nice to be able to set other values, not just updateStrategy type

See [this example](https://github.com/aws/aws-node-termination-handler/blob/main/config/helm/aws-node-termination-handler/templates/daemonset.linux.yaml#L11) for reference.

**Comment by paologallinaharbur** [comment]
Hello, @gdziwoki I totally agree feel free to propose a PR implementing it and I will be happy to review it 😄
