### ISSUE TITLE
[ci/cd] Implement yamllint or similar tool

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/helm-charts#416]
This FR is created as a follow up of https://github.com/newrelic/helm-charts/issues/407 and https://github.com/newrelic/helm-charts/issues/408

We noticed that the current linter is letting duplicate keys error passing, this is related to https://github.com/helm/helm/issues/5524. 

I raised again the concern in https://github.com/helm/chart-testing/issues/344 they suggested to use `yamllint` that we can leverage in the meanwhile in our pipeline in order to avoid such errors to happen in the future

Thanks again to @DWSR for raising the concern!

**Comment by kang-makes** [comment]
`chart-linter` uses `yamllint` under the hood.

I did a test and duplicated a YAML value in the `nri-bundle`:
```yaml
prometheus:
  enabled: false
  enabled: true

prometheus:
  enabled: true
```

And if failed:
```
Linting chart 'nri-bundle => (version: "4.3.3", path: "charts/nri-bundle")'
Validating /data/charts/nri-bundle/Chart.yaml...
Validation success! 👍
charts/nri-bundle/values.yaml
  8:3       error    duplication of key "enabled" in mapping  (key-duplicates)
  10:1      error    duplication of key "prometheus" in mapping  (key-duplicates)
```

Closing.
