### ISSUE TITLE
[nri-metadata-injection] only 1 cert is needed? but 2 certs are generated?

### ISSUE THREAD

**Issue by ghostsquad** [newrelic/helm-charts#442]
**Bug description**

multiple certificates are generated, including a root ca, and a certificate based on that CA, however, the root certificate is what is injected into the webhook, not the webhook certificate. Additionally, I think that the "job" that appears to "patch" the webhook is superfluous. Though, maybe it still exists for backwards compatibility? 

**Version of Helm and Kubernetes**

n/a

**Which chart?**

nri-metadata-injection

master branch

**What happened?**

n/a

**What you expected to happen?**

n/a

**How to reproduce it?**

n/a

**Anything else we need to know?**

Surprise us!

**Comment by paologallinaharbur** [comment]
Hello, yes there are two certificates, one is used in the [deployment](https://github.com/newrelic/helm-charts/blob/master/charts/nri-metadata-injection/templates/deployment.yaml) the ca certificate is used in the MutatingWebhookConfiguration to validate the requests.

Why is that superfluous?  It is needed to patch the ca, is there a better option from your point of view?

The approach is based on this opensource repo https://github.com/jet/kube-webhook-certgen

**Comment by ghostsquad** [comment]
@paologallinaharbur do you know the specifics of why the deployment requires a cert as well?

I'm just looking at other apps I have, such as the AWS Load Balancer Controller, and Datadog. They all have a mutating and/or validating webhook, and all use cert manager, and additionally, it looks like the all require just 1 cert, which makes the deployment simpler.

**Comment by paologallinaharbur** [comment]
The deployment uses the cert to [sign all requests](https://github.com/newrelic/k8s-metadata-injection/blob/46523b3fa11b5107ea684d1d46f9ff8fec59a212/cmd/server/main.go#L73), on the other hand the ca is used to validate that certificate.
```
    caBundle: "Ci0tLS0tQk...<`caBundle` is a PEM encoded CA bundle which will be used to validate the webhook's server certificate>...tLS0K"
```
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/

The caBundle can be left empty in case the deployment uses a "TLS certificate to be verified using system trust roots" and therefore that extra one is not needed. Since in this case a different CaRoot is used both are needed.

**Comment by paologallinaharbur** [comment]
Closing it for now, let me know if you have further doubts or a better architecture to propose :)

**Comment by kang-makes** [comment]
AFAIK it is already done: https://github.com/newrelic/k8s-metadata-injection/blob/main/charts/nri-metadata-injection/templates/admission-webhooks/mutatingWebhookConfiguration.yaml#L5-L9

Closing.
