### ISSUE TITLE
[nri-bundle] Add support for global imagePullSecrets

### ISSUE THREAD

**Issue by esteban1983cl** [newrelic/helm-charts#461]
**Is your feature request related to a problem? Please describe.**

Hello, I have a problem with deploy this chart, due Docker pull limits the installation doesn't finish ok for me
Example: 

chart version: 2.17.2 

```log
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  10m                  default-scheduler  Successfully assigned monitoring/green-newrelic-bundle-nri-metadata-injection-admission-creckth6 to ip-172-18-100-70.ec2.internal
  Normal   Pulling    8m43s (x4 over 10m)  kubelet            Pulling image "jettech/kube-webhook-certgen:v1.5.0"
  Warning  Failed     8m43s (x4 over 10m)  kubelet            Failed to pull image "jettech/kube-webhook-certgen:v1.5.0": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
  Warning  Failed     8m43s (x4 over 10m)  kubelet            Error: ErrImagePull
  Warning  Failed     5m8s (x22 over 10m)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    17s (x43 over 10m)   kubelet            Back-off pulling image "jettech/kube-webhook-certgen:v1.5.0"
```

**Describe the solution you'd like**

Please add support as other charts for global imagePullSecrets. Example:

```yaml
globalPullSecrets:
- my-pull-secrets
```

This configuration must be propagated to all subcharts and their manifests that use an image.
The admission webhooks job patches doesn't have this support.

**Describe alternatives you've considered**

Maybe move your images to a free registry ?

**Additional context**

This involves to all newrelic subcharts.

**Comment by mangulonr** [comment]
Hi Esteban

New Relic is working on a project together with Docker to remove this limit and also considering other alternatives to host our images.

I will ping you whenever we have updates.

Regards
