### ISSUE TITLE
Error when building through terraform

### ISSUE THREAD

**Issue by mraslam** [newrelic/helm-charts#486]
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "CatalogSource" in version "operators.coreos.com/v1alpha1", unable to recognize "": no matches for kind "OperatorGroup" in version "operators.coreos.com/v1", unable to recognize "": no matches for kind "Subscription" in version "operators.coreos.com/v1alpha1", unable to recognize "": no matches for kind "Vizier" in version "px.dev/v1alpha1"]

**Comment by sturman** [comment]
I have probably the same issue. 
Just tried to upgrade nri-bundle from 2.17.2 to 2.20.0 via ArgoCD and get the following errors
|KIND | NAMESPACE | NAME | STATUS | MESSAGE | 
|----------|-------------|------|------|-------|
|operators.coreos.com/v1alpha1/CatalogSource | px-operator | pixie-operator-index |  SyncFailed | the server could not find the requested resource | 
|operators.coreos.com/v1/OperatorGroup | px-operator | global-operators |  SyncFailed | the server could not find the requested resource | 
|operators.coreos.com/v1alpha1/Subscription | px-operator | pixie-operator-subscription |  SyncFailed | the server could not find the requested resource | 
|px.dev/v1alpha1/Vizier | newrelic | pixie |  SyncFailed | the server could not find the requested resource | 
|operators.coreos.com/v1/OperatorGroup | olm | olm-operators |  SyncFailed | the server could not find the requested resource

**Comment by mraslam** [comment]
@sturman It actually worked for me later. Previously, I was trying to deploy the helm chart without installing the CRD files which they mentioned. After deploying those it worked.

kubectl apply -f https://raw.githubusercontent.com/pixie-labs/pixie/main/k8s/operator/crd/base/px.dev_viziers.yaml -n monitoring-newrelic

kubectl apply -f https://raw.githubusercontent.com/pixie-labs/pixie/main/k8s/operator/helm/crds/olm_crd.yaml -n monitoring-newrelic

**Comment by mraslam** [comment]
Solved

**Comment by ipleten** [comment]
Why these aren't added to helm chart nor manifest? Is that any reason for that?
