### ISSUE TITLE
[pixie-operator-helm2-chart] Add NodeSelector

### ISSUE THREAD

**Issue by jdfalk** [newrelic/helm-charts#523]
**Is your feature request related to a problem? Please describe.**

Yes. We currently have several mixed clusters running windows and linux. The NRI/Pixie infra cannot run on the windows nodes but without nodeSelector in the chart we can't restrict them to linux nodes.

**Describe the solution you'd like**

Add nodeSelector to helm charts.

**Describe alternatives you've considered**

You could use taints but that creates a much bigger mess and ignores the Kubernetes provided solution that is nodeSelector

**Additional context**

This is related to #501 all the charts in this repo have the nodeSelector added but the pixie-operator-helm2-chart does not.

**Comment by smcavallo** [comment]
https://github.com/pixie-io/pixie/pull/359

**Comment by roobre** [comment]
This seems to have been fixed upstream in https://github.com/pixie-io/pixie/commit/6f0fba98451afb5659a6319a741450f20ca8fc43

Please feel free to reopen if this is not the case!
