### ISSUE TITLE
[NR-logging] RO /var mount causes FluentBit to fail creating its own DB.

### ISSUE THREAD

**Issue by schumacher-m** [newrelic/helm-charts#529]
Ref: https://github.com/newrelic/helm-charts/pull/472

We use AWS with EKS 1.20 and Helm 3. We have a system in place to apply changes based on SemVer and the latest 1.9 release triggered this again.
What happened now is that the FluentBit Process tries to create a file in /var/log  `flb_kube.db` which is not working anymore on a RO filesystem.

The pod now goes into a crashloop.

I do see a good reason for the PR. Nothing against that and I'd like to keep the RO flag.
A change in the config is probably needed now so it (fluentbit) does not try to write the file on the hostsystem. Or maybe that it even writes a file in the first place is a bug?!

**Comment by roobre** [comment]
Hi @schumacher-m! We noticed this yesteday and released version `1.10.0` fixing the issue, see: #532. Please tell us if this fixes the issue for you!

Regarding the original change, we are currently investigating further and see if there is a way to configure FluentBit to store the database somewhere else.

**Comment by schumacher-m** [comment]
Thanks for the quick rollout.
