### ISSUE TITLE
[nri-infrastructure] Modify the helm chart to support the new architecture

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/helm-charts#538]
Arch changed, we would need a daemonset and two deployments. Moreover the processed are long-running and sending data to a sidecar

Take care of reducing breaking changes, in case are 100% needed document those. Moreover:

- [ ] Provide a document explaining how to perform the migration if it is too complex. 
- [ ] modify requested memory and CPU advising customer in docs to notice the improvement
- [ ] Provide a way to modify the scraping interval
This configuration was requested multiple times, we could expose easily a parameter to manage that varning that cluster explorer experience might break

**Comment by paologallinaharbur** [comment]
We should provide -if possible- a way to map the old config to the new one easily. 

Old config should take precedence over the default values of the new one:

@alvarocabanas tentative in https://github.com/newrelic/nri-kubernetes/pull/267

```


{{- define "newrelic.deprecatedKubeStateMetrics" -}}
ksm:
  discovery:
      scheme: {{  $.Values.kubeStateMetricsScheme | quote }}
      port: {{  $.Values.kubeStateMetricsPort | quote }}
      static:
        url: {{  $.Values.kubeStateMetricsUrl | quote }}
      endpoints:
          label_selector: {{  $.Values.kubeStateMetricsPodLabel | quote }}
          namespace: {{  $.Values.kubeStateMetricsNamespace | quote }}
{{- end -}}

{{- define "config" -}}
{{ toYaml (merge (include "newrelic.deprecatedKubeStateMetrics" . | fromYaml) .Values.config) }}
{{- end }}
```

**Comment by alvarocabanas** [comment]
With the preceding solution if, for example,  $.Values.kubeStateMetricsScheme is empty, will be set as "" and the one from the .Values.config will be the one taken into account.
The only problem is understanding if the user really wants all and new values mixed, so we will have to discuss it further to understand which way we want to go.

**Comment by paologallinaharbur** [comment]
I do not like in the current proposal how the current config of the scraper is shared among all components. How someone would be able to change any shared config as the interval?
Moreover, since the config is shared now the `ksm.enabled/kubelet.enable/...` config is shared as well and therefore we need to do this [weird](https://github.com/newrelic/nri-kubernetes/blob/dd289d879a78fce0c44563352264b04f525a56b1/e2e/charts/newrelic-infrastructure/templates/daemonset-kubelet.yaml#L53) workaround. Discussing with @acabanas a solution would be to add commands through args. But I would still prefer to split the three configs for each component having in the values instead of [scraperConfig](https://github.com/newrelic/nri-kubernetes/blob/dd289d879a78fce0c44563352264b04f525a56b1/e2e/e2e-values.yml#L21):

```
ksmConfig:
  interval: 15s
  verbose: true
  timeout: 30s
  enabled: true

controlPlaneConfig:
  enabled: true
  interval: 15s
  verbose: true
  timeout: 30s
  apiServer:
    staticEndpoint:
      url: "https://localhost:8443"
  scheduler:
    staticEndpoint:
      url: "https://localhost:10259"
  controllerManager:
    staticEndpoint:
      url: "https://localhost:10257"
...

**Comment by alvarocabanas** [comment]
Yes, on my opinion, one thing is the configuration file and another is the execution mode of the binary.
The config file is common (it can have anyway split sections as Paolo suggests), but the binary should be executed with an argument, like : 
`nri-kubernetes kubelet`
`nri-kubernetes control-plane` 
or whatever, and then the code will be the one discarding what is not for that config, instead of having to set env vars to disable each one, because we don't want an execution doing more than one of the tasks.
This argument would not be handled by Viper but just with the standard library flag or whatever and is defined in an enum matching the config section.

**Comment by roobre** [comment]
Closed as per https://github.com/newrelic/helm-charts/pull/624
Killer job everyone!
