### ISSUE TITLE
newrelic-bundle-newrelic-pixie: CreateContainerConfigError

### ISSUE THREAD

**Issue by Aakankshi1** [newrelic/helm-charts#539]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
Events:
  Type     Reason  Age                        From     Message
  ----     ------  ----                       ----     -------
  Normal   Pulled  4m56s (x30819 over 4d15h)  kubelet  Container image "newrelic/newrelic-pixie-integration:1.4.0" already present on machine
  Warning  Failed  0s (x30842 over 4d15h)     kubelet  Error: secret "pl-cluster-secrets" not found

## Expected Behavior
newrelic-bundle-newrelic-pixie Pod should be available

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
Helm auto installer
kubectl apply -f https://raw.githubusercontent.com/pixie-labs/pixie/main/k8s/operator/crd/base/px.dev_viziers.yaml && \
kubectl apply -f https://raw.githubusercontent.com/pixie-labs/pixie/main/k8s/operator/helm/crds/olm_crd.yaml && \
helm repo add newrelic https://helm-charts.newrelic.com && helm repo update && \
kubectl create namespace newrelic ; helm upgrade --install newrelic-bundle newrelic/nri-bundle \
 --set global.licenseKey=********* \
 --set global.cluster=dev-app-deployment \
 --namespace=newrelic \
 --set newrelic-infrastructure.privileged=true \
 --set global.lowDataMode=true \
 --set ksm.enabled=true \
 --set prometheus.enabled=true \
 --set kubeEvents.enabled=true \
 --set logging.enabled=true \
 --set newrelic-pixie.enabled=true \
 --set newrelic-pixie.apiKey=********* \
 --set pixie-chart.enabled=true \
 --set pixie-chart.deployKey=********* \
 --set pixie-chart.clusterName=dev-app-deployment 

## Your Environment
EKS Cluster : T3.medium

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by roobre** [comment]
Hi there,

Thanks for filing this report! From the looks of the issue, there migth be a problem with the Pixie Operator, which is in charge of creating the `pl-cluster-secrets` secret that then is mounted by `newrelic-pixie-integration`.

In order to help with this we would need the logs and events for the pixie operator chart. Could you attech those here?

**Comment by Aakankshi1** [comment]
Hi Roberto,

Thank you for responding. I am afraid I no longer can provide you the logs. I re-installed helm charts and it worked. You may close the issue :)



regards
Aakankshi Gupta

**Comment by roobre** [comment]
Glad to see it worked in the end!
We'll take note and see if this pops up again, as we would expect it to work in the first try :)

Thanks!
