### ISSUE TITLE
[newrelic-logging] Allow command to be overridden

### ISSUE THREAD

**Issue by neilfordyce** [newrelic/helm-charts#564]
**Is your feature request related to a problem? Please describe.**

I would like to be able to override the command used to launch Fluent Bit so that I can pass alternative launch commands.  That would allow me to pass additional command line arguments to launch additional plugins or launch with a completely different command.

**Describe the solution you'd like**

Having the command defined in the values.yaml 

**Additional context**

We would like to launch Fluent Bit with [Fluent Bit Watcher](https://github.com/fluent/fluentbit-operator/blob/5694f2ac3fbf76525630bc363f79882937b71720/cmd/fluent-bit-watcher/Dockerfile).  This allows changes to the ConfigMap to trigger a restart of Fluent Bit and get the updated config.

Our specific requirement is to enable integration with existing internal tooling which we use to manage Kubernetes namespace quotas.  This will allow us to set throttling quotas using [Fluent Bit's throttling plugin](https://docs.fluentbit.io/manual/pipeline/filters/throttle) and automatically reload Fluent Bit when the throttling config changes.  This specific use case is probably quite niche, but imagine it could be more generally useful to pass different command line flags.

**Comment by danybmx** [comment]
Apologies @neilfordyce, closing this as explained in the PR #565

For the configMap configuration point, there is a PR already being reviewed #551

Thank you so much for your contribution and support

**Comment by neilfordyce** [comment]
Hey thanks for reviewing.  I've pulled in the changes from #511 to my fork already.  Trouble is, Fluent Bit doesn't automatically reload that config, so with #511 as it stands I need to restart the DaemonSet manually to propagate any changes to the ConfigMap.

Maybe that's the intention.  Fluent Bit Watcher is one solution to that problem.  If you want something more automatic in plain Helm, a common approach is to do something like hash the config in an annotation to trigger a deployment in response to changes, e.g. https://github.com/fluent/helm-charts/blob/ffed0f8ced630594f33d307839810282d8dafb5a/charts/fluent-bit/templates/daemonset.yaml#L26

**Comment by neilfordyce** [comment]
I've opened a new issue to consider the config updates separately #607
