### ISSUE TITLE
nri-metadata-injection namespaceSelector wrong nesting level

### ISSUE THREAD

**Issue by jrzdudek** [newrelic/helm-charts#57]
**Bug description**

The `namespaceSelector` field in the created `MutatingWebhookConfiguration` is nested on a wrong level. It should be on the same level as the `rules` field, as per <https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-namespaceselector> .

The chart wrongly generates it on the same level as a single rule. The effect is the `MutatingWebhookConfiguration` is created without the proper `namespaceSelector` element, making it impossible to restrict the injection to selected namespaces.

**Version of Helm and Kubernetes**

Helm: `v2.14.2`
Kubernetes: `v1.14.10-gke.36`

**Which chart?**

nri-metadata-injection `1.0.3`

**What happened?**

`MutatingWebhookConfiguration` was created without the proper `namespaceSelector` configuration.

**What you expected to happen?**

`MutatingWebhookConfiguration` created with:
```
  namespaceSelector:
    matchLabels:
      newrelic-metadata-injection: enabled
```

**How to reproduce it?**
As Helm values, use:
```
webhook:
  enabled: true
nri-metadata-injection:
  injectOnlyLabeledNamespaces: true
```
from the bundle chart, or:
```
injectOnlyLabeledNamespaces: true
```
from the chart itself.

**Anything else we need to know?**

One curious thing I don't understand is how the k8s API server doesn't error out when Helm creates the `MutatingWebhookConfiguration`, instead it just creates it with empty `namespaceSelector`. When applying the generated (eg. via `helm get`) Helm manifest manually I get an explicit API error, eg.:
```
error validating data: ValidationError(MutatingWebhookConfiguration.webhooks[0].rules[0]): unknown field "namespaceSelector" in io.k8s.api.admissionregistration.v1beta1.RuleWithOperations
```

**Comment by alejandrodnm** [comment]
@jrzdudek thanks for reporting this, It's already fixed
