### ISSUE TITLE
How to create external metrics without updating in values.yaml

### ISSUE THREAD

**Issue by mohanchazz** [newrelic/helm-charts#577]
I am using newrelic-k8s-metrics-adapter charts. Is there any way to setup additional external metrics without doing a helm upgrade by updating values.yaml file.

**Comment by paologallinaharbur** [comment]
If you you update the  values.yaml you will always need a "helm upgrade" in order to apply the changes.

To avoid running "helm upgrade" again, you could modify manually the configMap, however, you should avoid doing so with workloads/configs manages by k8s.

**Comment by mohanchazz** [comment]
@paologallinaharbur  I have tried to add a metrics in Configmap **_newrelic-k8s-metrics-adapter_**. But hpa unable to find the external metrics.

**Comment by paologallinaharbur** [comment]
can you share the config map yaml and the adapter verbose logs?

**Comment by mohanchazz** [comment]
Below the hpa, The 3rd metrics is configured by editing CM.

`apiVersion: v1
data:
  config.yaml: |
    accountID: ******
    cacheTTLSeconds: 30
    externalMetrics:
      cpu_util:
        query: from K8sContainerSample SELECT average(requestedCpuCoresUtilization)
      memory_util:
        query: from K8sContainerSample SELECT average(memoryUtilization)
      memory:
        query: from K8sContainerSample SELECT latest(memoryRequestedBytes)
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: newrelic-k8s-metrics-adapter
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2021-11-09T05:50:42Z"
  labels:
    app.kubernetes.io/instance: newrelic-k8s-metrics-adapter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: newrelic-k8s-metrics-adapter
    app.kubernetes.io/version: 0.1.0
    helm.sh/chart: newrelic-k8s-metrics-adapter-0.1.0
  name: newrelic-k8s-metrics-adapter
  namespace: monitoring
  resourceVersion: "7506650"
  selfLink: /api/v1/namespaces/monitoring/configmaps/newrelic-k8s-metrics-adapter
  uid: 7fdffffa-bd16-4f62-a54b-09961bbb2b4b`


**Events of hpa:** 

Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetExternalMetric  the HPA was unable to compute the replica count: unable to get external metric jen/memory/nil: unable to fetch metrics from external metrics API: getting fresh external metric value: getting metric value: metric "memory" not configured
Events:
  Type     Reason                        Age   From                       Message
  ----     ------                        ----  ----                       -------
  Warning  FailedGetExternalMetric       13s   horizontal-pod-autoscaler  unable to get external metric jen/memory/nil: unable to fetch metrics from external metrics API: getting fresh external metric value: getting metric value: metric "memory" not configured
  Warning  FailedComputeMetricsReplicas  13s   horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get external metric memory: unable to get external metric jen/memory/nil: unable to fetch metrics from external metrics API: getting fresh external metric value: getting metric value: metric "memory" not configured

**Adapter logs:**
I1118 05:36:13.181004       1 main.go:137] Starting NewRelic metrics adapter
time="2021-11-18T05:36:13Z" level=warning msg="unknown region, using default: US"
I1118 05:36:13.181756       1 provider.go:68] Registering metric "cpu_util"
I1118 05:36:13.181766       1 provider.go:68] Registering metric "memory_util"
I1118 05:36:13.181771       1 provider.go:71] All queries will be executed for account ID 3020404
I1118 05:36:13.665067       1 genericapiserver.go:419] [graceful-termination] ShutdownTimeout=1m0s
I1118 05:36:13.671530       1 requestheader_controller.go:169] Starting RequestHeaderAuthRequestController
I1118 05:36:13.671563       1 shared_informer.go:240] Waiting for caches to sync for RequestHeaderAuthRequestController
I1118 05:36:13.671583       1 configmap_cafile_content.go:201] "Starting controller" name="client-ca::kube-system::extension-apiserver-authentication::client-ca-file"
I1118 05:36:13.671614       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I1118 05:36:13.671831       1 configmap_cafile_content.go:201] "Starting controller" name="client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file"
I1118 05:36:13.672002       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I1118 05:36:13.672131       1 dynamic_serving_content.go:129] "Starting controller" name="serving-cert::/tmp/k8s-metrics-adapter/serving-certs/tls.crt::/tmp/k8s-metrics-adapter/serving-certs/tls.key"
I1118 05:36:13.672206       1 secure_serving.go:256] Serving securely on [::]:6443
I1118 05:36:13.672241       1 genericapiserver.go:378] [graceful-termination] waiting for shutdown to be initiated
I1118 05:36:13.672309       1 tlsconfig.go:240] "Starting DynamicServingCertificateController"
I1118 05:36:13.771876       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file 
I1118 05:36:13.771878       1 shared_informer.go:247] Caches are synced for RequestHeaderAuthRequestController 
I1118 05:36:13.772211       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file 
I1118 05:36:23.408426       1 trace.go:205] Trace[939984059]: "List" url:/apis/external.metrics.k8s.io/v1beta1/namespaces/jen/cpu_util,user-agent:kube-controller-manager/v1.19.13 (linux/amd64) kubernetes/ddb8dba/system:serviceaccount:kube-system:horizontal-pod-autoscaler,audit-id:45e27a46-36e3-400d-9c4d-20fcc59e273f,client:172.31.18.138,accept:application/vnd.kubernetes.protobuf, */*,protocol:HTTP/2.0 (18-Nov-2021 05:36:22.697) (total time: 710ms):
Trace[939984059]: ---"Listing from storage done" 710ms (05:36:23.408)
Trace[939984059]: [710.411731ms] [710.411731ms] END
I1118 06:58:51.013591       1 trace.go:205] Trace[126960631]: "List" url:/apis/external.metrics.k8s.io/v1beta1/namespaces/jen/cpu_util,user-agent:kube-controller-manager/v1.19.13 (linux/amd64) kubernetes/ddb8dba/system:serviceaccount:kube-system:horizontal-pod-autoscaler,audit-id:eace5639-a2bb-460b-87ac-29034db7cb9c,client:172.31.18.138,accept:application/vnd.kubernetes.protobuf, */*,protocol:HTTP/2.0 (18-Nov-2021 06:58:50.270) (total time: 742ms):
Trace[126960631]: ---"Listing from storage done" 742ms (06:58:51.013)
Trace[126960631]: [742.698771ms] [742.698771ms] END
E1118 09:51:01.848500       1 status.go:71] apiserver received an error that is not an metav1.Status: &fmt.wrapError{msg:"getting fresh external metric value: getting metric value: metric \"memory\" not configured", err:(*fmt.wrapError)(0xc000149180)}: getting fresh external metric value: getting metric value: metric "memory" not configured
E1118 09:51:16.899961       1 status.go:71] apiserver received an error that is not an metav1.Status: &fmt.wrapError{msg:"getting fresh external metric value: getting metric value: metric \"memory\" not configured", err:(*fmt.wrapError)(0xc00069c6e0)}: getting fresh external metric value: getting metric value: metric "memory" not configured

**Comment by paologallinaharbur** [comment]
Have you restarted the pod to exclude any cache/hot-reload issues?

By the way I reopened the issue to take a closer look. Anyway the recommended way to apply changes it to modify the  values.yaml and upgrade

**Comment by mohanchazz** [comment]
Yes, Pod restart able to solve the issue. Would be much better without a need of pod restart or helm upgrade in our case.

**Comment by paologallinaharbur** [comment]
I agree, can you open a Feature Request in the repo https://github.com/newrelic/newrelic-k8s-metrics-adapter mentioning this issue?

The pod can be restarted automatically by adding an hash of the configmap when upgrading, or even better the application should support hot-releoading

**Comment by mohanchazz** [comment]
Sure , Thanks.
