### ISSUE TITLE
[nri-bundle] KSM creates noisy logs in Kubernetes 1.22

### ISSUE THREAD

**Issue by roobre** [newrelic/helm-charts#582]
KSM `1.9.8` will attempt to fetch beta resources that no longer exist in `1.22`. which causes log messages like the following to be emmited frequently:

```
E1109 16:56:14.735035       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1beta1.CertificateSigningRequest: the server could not find the requested resource
```

This creates noise and should be avoided.

**Comment by paologallinaharbur** [comment]
An easy fix should be removing --collectors=certificatesigningrequest from the KSM default config
