### ISSUE TITLE
[nri-bundle] Add example about config maps and mount points for nri-jmx config by annotations

### ISSUE THREAD

**Issue by rubenruizdegauna** [newrelic/helm-charts#586]
`nri-jmx` can be configured using k8s annotations:
https://github.com/newrelic/nri-jmx/pull/90

It would be nice to have an example in https://github.com/newrelic/helm-charts/blob/c8a3d8042dd85c757cb0d3ba1b00eea20d24ebf6/charts/nri-bundle/values.yaml#L88

Thanks!!

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
