### ISSUE TITLE
Error installing into azure kubernetes

### ISSUE THREAD

**Issue by R-Lamberson** [newrelic/helm-charts#606]
Attempting to install newrelic-bundle into azure kubernetes environment (version 1.20.7)

Helm install timeouts out however I am able to see the following error message in nri-metadata-inject-admission-create pod

![image](https://user-images.githubusercontent.com/48865653/143311242-5f5ad543-7438-4e80-b428-7c62e9a7bbfc.png)

This AKS environment has two node pools one linux for the system plane and one windows for the application plane.

I attempted to set the nodeSelector in the newrelic-infrastructure to prefer linux but this was not successful.   If there is any guidance for installing in a hybrid environment it would be appreciated

**Comment by roobre** [comment]
Hi there,

Unfortunately we do not offer support for windows nodes on our solution. It is possible to configure the `newrelic-infrastructure` chart to run on windows nodes, but this is an experimental feature we cannot offer help for.

However, it would seem to me that the issue you are having is not with `newrelic-infrastructure` chart, but with `newrelic-metadata-injection`. You can disable this component from the `nri-bundle` chart by specifying `webhook.enabled: false`.

This webhook takes care of allowing New Relic language agents (e.g. Java, Ruby, Go, etc). to become aware of the K8s pods and containers they are running, which later results in a richer APM experience. If you are not using APM, you might disable the webhook without problems.

**Comment by R-Lamberson** [comment]
Ok thanks for the information
