### ISSUE TITLE
[newrelic-logging] changes to ConfigMap don't propogate until restart

### ISSUE THREAD

**Issue by neilfordyce** [newrelic/helm-charts#607]
**Is your feature request related to a problem? Please describe.**

It's possible to configure Fluent Bit via Helm since #593 made ConfigMaps configurable.  However, the changes don't propagate automatically and only take effect when Fluent Bit restarts.  

For example, if I wanted to add a new input to `fluentBit.config.inputs`, I can add it to the ConfigMap, but I'd need to manually restart Fluent Bit to make it pickup  the changes.  Manually restarting DaemonSets across many clusters is toilsome and worth automating.  

**Describe the solution you'd like**

Open to ideas.  A common approach is to add a hash of the configmap to pod annotations to trigger a deployment when the configmap changes, e.g. https://github.com/fluent/helm-charts/blob/ffed0f8ced630594f33d307839810282d8dafb5a/charts/fluent-bit/templates/daemonset.yaml#L26

**Describe alternatives you've considered**

Fluent Bit operator solves it by using Fluent Bit watcher, launch Fluent Bit as a child process and restart it when the config changes.

**Comment by danybmx** [comment]
This was fixed on https://github.com/newrelic/helm-charts/pull/906, closing this issue.
