### ISSUE TITLE
[newrelic-infrastructure] Deprecate openShift 3.x

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/helm-charts#611]
According to [the docs](https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements/) "Kubernetes cluster OpenShift | Currently tested with versions 4.6".

However, the chart has in the values openshift.version including 3.x and changing it behaviour to support it. If it is deprecated we should be thinking to remove that soon.

According to redHat:

<img width="800" alt="Screen Shot 2021-12-01 at 4 30 09 PM" src="https://user-images.githubusercontent.com/43335750/144263358-0f1220cd-f870-4bad-b273-ee2c6ecc7e5f.png">

**Comment by roobre** [comment]
Do we still have this specifics in the `v3` chart @paologallinaharbur ?

**Comment by paologallinaharbur** [comment]
no!
