### ISSUE TITLE
[newrelic-logging] Allow additionalEnvVars that use valueFrom

### ISSUE THREAD

**Issue by annettejanewilson** [newrelic/helm-charts#613]
At present it's possible to provide `additionalEnvVars` to set [environment variables][1] on the Fluent Bit container. However, these can only be provided as value strings. There's no provision to allow an [EnvVarSource][2]. For example, we would like to pass in the pod name as an environment variable to make use of in the FluentBit configuration file:

```
additionalEnvVars:
- name: K8S_POD_NAME
  valueFrom:
    fieldRef:
      fieldPath: metadata.name
```

The root of this appears to be [this code in the chart][3] that iterates over `additionalEnvVars` and explicitly looks for the "value" field and uses it to create a new object with a name and a value field.
```
{{- range .Values.fluentBit.additionalEnvVariables }}
- name: {{ .name }}
  value: {{ .value }}
{{- end }}
```
If this instead passed through the environment items unmodified (or explicitly passed through the valuesFrom field) this would enable setting such metadata-derived environment variables.

**Is your feature request related to a problem? Please describe.**

I want to use the pod name in the Fluent Bit configuration, specifically to set it as a label on metrics emitted by the prometheus remote write plugin. Since every pod has a different name, I can't set this via a static environment variable. It needs to be derived from the metadata.

**Describe the solution you'd like**

I want the chart to pass through each item in `additionalEnvVars` directly.

**Describe alternatives you've considered**

A hard-coded environment variable set to the pod name would also solve my immediate problem, but it wouldn't be very general.

**Additional context**

See also https://github.com/newrelic/helm-charts/issues/81 which would benefit from such a change.

[1]: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#envvar-v1-core
[2]: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#envvarsource-v1-core
[3]: https://github.com/newrelic/helm-charts/blob/334ce7ae4e9753acea9e35c5b923a6795cea262e/charts/newrelic-logging/templates/daemonset.yaml#L87-L90

**Comment by achupryn** [comment]
Hello NR team, do you have any news regarding that feature request?

we also need that functionality to add env vars from k8s secrets (credentials for additional output) - https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

Thanks
