### ISSUE TITLE
[nri-bundle] - Add an option to add Tolerations to the helm chart

### ISSUE THREAD

**Issue by vikas027** [newrelic/helm-charts#633]
**Is your feature request related to a problem? Please describe.**
I have some taints on my nodes which are not tolerated by some pods

![2021-12-30_14-53-15](https://user-images.githubusercontent.com/6998650/147720391-001f7600-a76c-459f-8957-4f392742d554.png)

A clear and concise description of what the problem
Pods are unable to tolerate the taints

**Describe the solution you'd like**
It would be great to have `tolerations` in the [values](https://github.com/newrelic/helm-charts/blob/master/charts/nri-bundle/values.yaml) file.

**Describe alternatives you've considered**
Add a Kustomization ;)

**Comment by roobre** [comment]
To be tackled during https://github.com/newrelic/newrelic-coreint/issues/256, planned for this quarter.

**Comment by kang-makes** [comment]
Charts had been integrated with the common library, any chart should honor `.global.tolerations`, `.global.affinity`, and `.global.nodeSelector`.

Closing.
