### ISSUE TITLE
infrastructure v3: Implenent the compatibility layer

### ISSUE THREAD

**Issue by roobre** [newrelic/helm-charts#636]
To ease the transition between `nri-kubernetes` v2 and v3 we will add a set of helpers that translate or validate values form the old to the new chart. So far we have two approaches, both of which I think acceptable:
1. Rename the chart and not add a compatibility helper
2. Keep the old name for the chart and add a compatibility helper

### Option 1 The discarded one
Rename and avoid helper:
We would add the new chart with a new name. In the bundle chart, a helper would perform very basic sanity checks:
- Fail if both old and new are enabled (unlikely to happen)
- Fail if the old chart has any kind of config that does not have an equivalent in the new one.

This makes the upgrade process safe: We will fail and point the user to a simple migration guide if they have complex config. For simple things, like the privileged flag, we check they are equal and go ahead. If more complex options are set, we just fail and point to the migration guide.
Here we assume that most customers will not have custom values. If this is the case, the migration does not need intervention in the happy path. (edited) 

### Option 2 The chosen one

Keep name and add helper:
- We add the new chart, `newrelic-infrastructure-beta` aliased as `newrelic-infrastructure`.
- We add a helper that translates the values and emits a deprecation warning.
In the future, we rename `newrelic-infrastructure-beta` with `newrelic-infrastructure`, making the change breaking after some time.
This will make us stick with the old name.

**Comment by paologallinaharbur** [comment]
Option 2 has been chosen, in particular:
 - regarding the compatibility layer we decided to timebox it and if needed we can simply error at upgrading time pointing to docs showing how to translate values
