### ISSUE TITLE
[newrelic-bundle] use of multiple licenses in the same daemon set

### ISSUE THREAD

**Issue by ilyagorban-codefresh** [newrelic/helm-charts#646]
**Is your feature request related to a problem? Please describe.**

We need to collect logs and metrics for 2 different NewRelic accounts from the same cluster, to be chosen by namespace or labels. Filtering out metrics/logs in the same account is not a good option for us.

Current chart's templates does not allow to set multiple license keys.

**Describe the solution you'd like**

Add to charts of logging and metrics charts (and additional dependent on it charts) map of license keys to fluentbit filters and kube-metrics namespaces to use with this license keys.

**Describe alternatives you've considered**

Our current solution: deployment of 2 different daemon sets to use 2 different NewRelic license keys. But it uses additional resources and makes duplication of configuration in helmfile / helm.

**Additional context**

**Comment by roobre** [comment]
Hey there,

Thanks a lot for your suggestion! I believe this should be a responsibility of the https://github.com/newrelic/infrastructure-agent. @mangulonr will raise a feature request to the agent team for this.

However for the chart this would be out of scope, therefore I'll close this issue.
