### ISSUE TITLE
[nri-bundle] - Add an option to specify docker images and tags

### ISSUE THREAD

**Issue by vikas027** [newrelic/helm-charts#648]
**Is your feature request related to a problem? Please describe.**
My organization does not want to pull images from docker hub directly and would like to pull them from a private docker repository

**Describe the solution you'd like**
It would be great to have the option to define the same in [values](https://github.com/newrelic/helm-charts/blob/master/charts/nri-bundle/values.yaml) file.

**Describe alternatives you've considered**
- Add a Kustomization 
- Clone the repo and make changes

**Comment by roobre** [comment]
Support for overriding image name, tag, and repository has been implemented in the `newrelic-infrastructure` v3 chart: #624
The same feature is planned to land into the rest of the charts this quarter :)
