### ISSUE TITLE
nri-bundle open CVEs on nri-kube-events container image

### ISSUE THREAD

**Issue by aroommen** [newrelic/helm-charts#677]
**Bug description**

Containers images that we use from the nri-bundle have been consistently failing security scans with trivy (https://github.com/aquasecurity/trivy) due to open CVEs. 

**Version of Helm and Kubernetes**
$ helm version
version.BuildInfo{Version:"v3.5.1", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.7"}

**Which chart?**
nri-bundle-3.3.1

**What happened?**
These are the containers that we use from the nri-bundle which have open CVEs
newrelic-fluentbit-output - 1.10.0 
nri-kube-events - 1.6.0 

**What you expected to happen?**
We expect the security scan to pass on all the containers we scan from the nri-bundle

**How to reproduce it?**
$ trivy image newrelic/newrelic-fluentbit-output:1.10.0 
$ trivy image newrelic/nri-kube-events:1.6.0

Steps to reproduce the problem, as minimally and precisely as possible.
Run the trivy commands listed above and inspect the CVEs listed by trivy

**Anything else we need to know?**
Could you upgrade the nri-kube-events bundle to use the 1.7.0 version which currently has no open CVEs.

**Comment by davidgit** [comment]
Closing this ticket because it was solved a few days ago.
