### ISSUE TITLE
[all] Create a separate chart for `kube-webhook-certgen`

### ISSUE THREAD

**Issue by roobre** [newrelic/helm-charts#701]
**Is your feature request related to a problem? Please describe.**

We currently use the images from `ingress-nginx/kube-webhook-certgen` to create, sign, and patch certificates for webhooks that we deploy. Specifically, this is done by https://github.com/newrelic/helm-charts/tree/master/charts/nri-metadata-injection, https://github.com/newrelic/helm-charts/tree/master/charts/newrelic-k8s-metrics-adapter, and https://github.com/newrelic/helm-charts/tree/master/charts/newrelic-infra-operator.

Those three chart essentially have a duplicated copy of the required manifests, which makes hard to keep them up to date and in sync.

**Describe the solution you'd like**

We could explore the possibility of creating a separate chart containing just this hook, and their own set of values and tests.

**Comment by roobre** [comment]
In wonder if upstream will be interested in having this in the `ingress-nginx` repo. Do you happen to have any thoughts on this @invidian?

**Comment by invidian** [comment]
I guess something like https://github.com/surajssd/helm-charts/tree/main/charts/automatic-webhook-certificates would be desired. CC @surajssd :wink: 

I think it would be nice to have something like this upstream, it makes part reusable and testable. I imagine later on this could also be pulled into kube-prometheus-stack and possibly other charts using webhooks.
