### ISSUE TITLE
[newrelic-logging] appVersion not in sync with newrelic/newrelic-fluentbit-output images

### ISSUE THREAD

**Issue by andrew-lozoya** [newrelic/helm-charts#706]
Please update the appVersion to match the release cycles of newrelic/newrelic-fluentbit-output images. These are out of sync in the field. 

appVersion:
https://github.com/newrelic/helm-charts/blob/3043d8d65e6ed21059e036576be5c0f6b7a05891/charts/newrelic-logging/Chart.yaml#L5

The template that references appVersion:
https://github.com/newrelic/helm-charts/blob/3043d8d65e6ed21059e036576be5c0f6b7a05891/charts/newrelic-logging/templates/daemonset.yaml#L44

The newrelic/newrelic-fluentbit-output hub:
https://hub.docker.com/r/newrelic/newrelic-fluentbit-output/tags

**Comment by jsubirat** [comment]
Back in sync
