### ISSUE TITLE
[nri-bundle] slow horizontal pod autoscaling and deploy rollout

### ISSUE THREAD

**Issue by kiwiaddo** [newrelic/helm-charts#708]
We are finding that performance of the horizontal pod auto-scaler (in GKE) is severely impacted by upgrading to the `nri-bundle` (5-10x slower). Upgrading the individual components `kube-state-metrics` and `newrelic-infrastructure` to the latest version does not seem to have the same impact. Other telemetry and instrumentation seems to be unaffected (i.e. dashboards etc) and logs in GKE do not seem to yield anything different either.

This works as expected:
```
resource "helm_release" "kube-state-metrics" {
  name       = "kube-state-metrics"
  repository = "https://charts.helm.sh/stable"
  chart      = "kube-state-metrics"
  version    = "2.9.4"
  namespace  = "kube-system"
}

# https://github.com/newrelic/helm-charts
resource "helm_release" "newrelic-infra" {
  name       = "new-relic"
  repository = "https://helm-charts.newrelic.com"
  chart      = "newrelic-infrastructure"
  version    = "2.8.0"
  namespace  = "kube-system"

  set {
    name  = "cluster"
    value = local.new_relic_cluster_name
  }

  set {
    name = "priorityClassName"
    value = "system-node-critical"
  }

  set_sensitive {
    name  = "licenseKey"
    value = var.new_relic_license
  }
}
```
This does not
```
resource "helm_release" "newrelic_infra_bundle" {
  name       = "new-relic"
  chart      = "nri-bundle"
  repository = "https://helm-charts.newrelic.com"
  version    = "3.3.5" 
  namespace  = "kube-system"

  set {
    name  = "global.cluster"
    value = local.new_relic_cluster_name
  }

  set_sensitive {
    name  = "global.licenseKey"
    value = var.new_relic_license
  }

  set {
    name  = "infrastructure.enabled"
    value = "true"
  }

  set {
    name  = "ksm.enabled" 
    value = "true"
  }

  set {
    name = "priorityClassName"
    value = "system-node-critical"
  }
}
```

**Comment by roobre** [comment]
Hey @kiwiaddo, that's certainly unexpected. Something that comes to my mind as a possible root cause would be the [metadata-injection](https://github.com/newrelic/helm-charts/tree/master/charts/nri-metadata-injection) webhook as I explained above.

Would it be possible for you to try to deploy the bundle again, but turn this particular component off? You can do this by setting 
```yaml
webhook:
  enabled: false
```
in your values file for the `nri-bundle` chart.

If we determine this is the offending component we can keep troubleshooting it or just leave it disabled, if you are not using it in your setup.

**Comment by kiwiaddo** [comment]
Hi @roobre 
Turning off that component (`webhook.enabled`) does seem to fix the problem. Using the nri-bundle with that setting turned off results in normal rollout speeds

**Comment by davidgit** [comment]
Hi , 

The next best step is to visit [New Relic Support](https://support.newrelic.com/), where you can engage the New Relic Support Community or open a support ticket depending on your support level. The support team is best positioned to assist with your specific needs. 

Please provide a link to this GitHub issue when submitting your community post or support ticket.

Thanks!
