### ISSUE TITLE
[newrelic-infrastructure-v3] AWS EKS Instructions?

### ISSUE THREAD

**Issue by ghostsquad** [newrelic/helm-charts#715]
It appears as thought the controlplane for `newrelic-infrastructure-v3` wants to run on the master nodes. This is not possible on AWS EKS. Is AWS EKS going to be supported?

**Comment by kang-makes** [comment]
Hi @ghostsquad,

Yes, the integration itself is supported in all the flavors of Kubernetes. The Control Plane monitoring is tricky as it could change depending on the flavor and where it is located.

Please, [refer to the docs](https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/configure-control-plane-monitoring/#cloud-control-plane) where how to monitor the control plane in cloud environments is explained.

Regards.
