### ISSUE TITLE
[nri-kube-events] attempting to write warnings to RO filesystem

### ISSUE THREAD

**Issue by paul91** [newrelic/helm-charts#72]
`nri-kube-events`'s `kube-events` container keeps crashing every few minutes as a watch warning causes the service to try to write to `/tmp`, which is a readonly filesystem. I am not sure if this is necessarily a bug in `kube-events` or the container should just be updated to allow it to write to a tmpfs like the side-car `infra-agent` container already can.

**Version of Helm and Kubernetes**

```
$ kubectl version
...
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
$ helm version
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

**Which chart?**

`nri-kube-events` / `kube-events`

**What happened?**

When any of the watchers emit a warning, it attempts to log it to `/tmp`. This is a read-only filesystem which causes the container to crash and restart.

```
W0623 14:41:44.507228       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.Event ended with: The resourceVersion for the provided watch is too old.
log: exiting because of error: log: cannot create log: open /tmp/nri-kube-events.newrelic-events-nri-kube-events-c6bfbd6ff-6bm5s.nri-kube-events.log.WARNING.20200623-144144.1: read-only file system
```

**What you expected to happen?**

`kube-events` warnings shouldn't cause the container to restart. This should either be made into a writable directory or `kube-events` should only send warnings to stdout.

**How to reproduce it?**

This is just a generic Rancher deployed K8s cluster on v1.17.4

**Comment by rbabyuk** [comment]
I hit the same issue, it's weird as /tmp is mounted and 'emptydir' and 'readonly' flag is not set, meaning 'readonly' is `false` by default.
