### ISSUE TITLE
[newrelic-logging] New FILTER "grep" rule doesn't work

### ISSUE THREAD

**Issue by jsubirat** [newrelic/helm-charts#77]
**Bug description**

[Originally posted by @d00m178 in the [deprecated kubernetes-logging repository](https://github.com/newrelic/kubernetes-logging/issues/34)]

I have changed the filter-kubenetes.con part in fluent-conf.yml:
```
  filter-kubernetes.conf: |
    [FILTER]
        Name record_modifier
        Match *
        Record cluster_name ${CLUSTER_NAME}

    [FILTER]
        Name           kubernetes
        Match          kube.*
        Kube_URL       https://kubernetes.default.svc.cluster.local:443
        Merge_JSON_Log Off

    [FILTER]
        Name grep
        Match *
        Exclude message HealthChecker
```
And want to exclude log messages like:
172.18.110.109 - - [29/May/2020:13:02:35 +0000] "GET / HTTP/1.1" 200 2804 "-" "ELB-HealthChecker/2.0" "-"

But seem it doesn't work - such log messages still coming to NR Logs page.
Also I checked:

`Exclude log HealthChecker`
the same behavior.
Please advice - is the Filter rules works in New Relic Fluent Bit output plugin for Kubernetes?

**Version of Helm and Kubernetes**

The version of Helm and Kubernetes where the problem occurs.

**Which chart?**

The chart name and version.

**What happened?**

Described what happened, as detailed as possible and necessary.

**What you expected to happen?**

Please avoid saying "It should just work".

**How to reproduce it?**

Steps to reproduce the problem, as minimally and precisely as possible.

**Anything else we need to know?**

Surprise us!

**Comment by jsubirat** [comment]
Hi @d00m178, can you please fill in the sections in the description above? Many thanks!

**Comment by jsubirat** [comment]
Hi @d00m178, could you please fill the sections in the description above? Many thanks in advance.

**Comment by luckslovez** [comment]
Unless a custom parser is being used and thus the `message` field is assured to be present, there won't be such field. The default field is log. Using the following works fine;
```
[FILTER]
Name grep
Match *
Exclude log /INFO/
```

Please feel free to reopen if the issue persists
