### ISSUE TITLE
[ci/cd] release multiple charts

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/helm-charts#782]
We found a small “bug” into the chart release. 

[Since we release](https://github.com/newrelic/helm-charts/blob/134dbd6f3bcd74ae6aa3af9cf08f6fdd118ed487/.github/workflows/release.yml#L55) library and then charts if you merge a PR with both -> only libraries are released since the first step creates a tag. 

Therefore now it is not possible to release at the same time library chart and "normal" ones

**Comment by kang-makes** [comment]
There is no way to fix the CI to fix it without making a contribution to the action itself.

The action can only get one folder: https://github.com/helm/chart-releaser-action/blob/a3454e4/cr.sh#L250
```shell
    local commit="$1"

    local changed_files
    changed_files=$(git diff --find-renames --name-only "$commit" -- "$charts_dir")

    local depth=$(( $(tr "/" "\n" <<< "$charts_dir" | sed '/^\(\.\)*$/d' | wc -l) + 1 ))
    local fields="1-${depth}"

    cut -d '/' -f "$fields" <<< "$changed_files" | uniq | filter_charts
```

As `$charts_dir` is quoted we cannot set more than one folder there. If we try to workaround it with something like putting there a `.` the `cut` command above will leave the charts out of the scope.

```
Looking up latest tag...
Discovering changed charts since 'nri-bundle-3.6.5'...
WARNING: .github/Chart.yaml is missing, assuming that '.github' is not a Helm chart. Skipping.
WARNING: charts/Chart.yaml is missing, assuming that 'charts' is not a Helm chart. Skipping.
WARNING: library/Chart.yaml is missing, assuming that 'library' is not a Helm chart. Skipping.
Nothing to do. No chart changes detected.
```

I have the time to improve the charts and the release process timeboxed so I have to low the priority of this issue.

I leave this comment to give context for the next who can take it.
