### ISSUE TITLE
[nri-bundle] Update local dependencies to External URL's

### ISSUE THREAD

**Issue by shawnj** [newrelic/helm-charts#796]
**Is your feature request related to a problem? Please describe.**

When trying to package up our `nri-bundle` for delivery to Rancher Partner Charts, the local dependencies in the `requirements.yaml` file cause the packaging function to fail.  In order for us to package the `nri-bundle` for consumption of Rancher customers that want to install New Relic we would need to convert the local dependencies to external URL based locations.

**Describe the solution you'd like**

Currently, the `newrelic-k8s-metrics-adapter` follows this pattern.  I would like the remaining dependencies to be updated to remote repositories.

**Additional context**

This is the Rancher `Parner-Charts` repo that is used to prepare/package helm charts for delivery to their Rancher App Marketplace. https://github.com/rancher/partner-charts

**Comment by kang-makes** [comment]
I am reopening it because it is a solution ongoing but is not merged yet so it is an issue (yet)

**Comment by kang-makes** [comment]
We finally GA the latest version of Kubernetes integration ant the PR changed all de dependency repositories to URLs:
https://github.com/newrelic/helm-charts/pull/795/files#diff-5b5b4e84ee5774a52ded11c1661f97bc829a6a562d2e5c20eb28b77162893340R20-R70

Closing :)
