### ISSUE TITLE
[newrelic-logging] Add support for OpenShift (OKD)

### ISSUE THREAD

**Issue by jsubirat** [newrelic/helm-charts#80]
**Is your feature request related to a problem? Please describe.**

[Originally extracted from this feature request posted by @tetsushiawano in the [deprecated kubernetes-logging repository](https://github.com/newrelic/kubernetes-logging/issues/16)]

Please add support for OpenShift (OKD). A proposal on how to implement this was provided for the manual K8s manifests [here](https://github.com/newrelic/kubernetes-logging/issues/16#issuecomment-564805070).

**Describe the solution you'd like**

A proposal on how to implement this was provided for the manual K8s manifests [here](https://github.com/newrelic/kubernetes-logging/issues/16#issuecomment-564805070).

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by jsubirat** [comment]
Hi @tetsushiawano, I'd like to let you know that we currently support OpenShift: https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure/#install-openshift-container-platform

I'm therefore closing this ticket.

**Comment by tetsushiawano** [comment]
Oh great. Thank you for notice!
