### ISSUE TITLE
[nri-bundle] Enable KSM by default

### ISSUE THREAD

**Issue by roobre** [newrelic/helm-charts#819]
While originally our integration relied on the user to provide their own version of KSM, with time we have seen that most users prefer for the `nri-bundle` chart to contain, by default, the minimum amount of dependencies required by the integration to run.

As KSM is now disabled by default, advanced users that install the chart directly (as opposed to following our docs step by step, or the guided install) will have a broken experience by default, unless they happen to have a KSM instance around in their cluster.

To solve this, we could turn the KSM dependency on by default.

As a follow-up, this would also allow us to:
1. From the `nri-bundle` chart, specify a custom label for KSM, and remove the prometheus annotation for it
2. From the `nri-bundle` chart, override the labelSelector of the `nri-kubernetes` chart so it looks up for _our_ KSM instance first

**Comment by svetlanabrennan** [comment]
You can enable ksm in nri-bundle by updating the values.yaml file: https://github.com/newrelic/helm-charts/blob/master/charts/nri-bundle/values.yaml#L18
