### ISSUE TITLE
[newrelic-bundle] nri-bundle-4.4.7 missing APP VERSION in the chart

### ISSUE THREAD

**Issue by soumyaparui** [newrelic/helm-charts#840]
![image](https://user-images.githubusercontent.com/28701929/170396117-cb9f3ed0-d91f-4f6d-89e7-2fe5548f9532.png)

**Comment by paologallinaharbur** [comment]
Hello!
`nri-bundle` chart is an umbrella collecting different subcharts therefore that hardcoded appVersion did not have any meaning and this is why it was removed.

**Comment by paologallinaharbur** [comment]
Feel free to reopen in case the missing appVersion is causing any issue
