### ISSUE TITLE
[all] mergeOverwrite behaviour

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/helm-charts#858]
[Context](https://msitko.pl/blog/2021/01/07/a-few-problems-with-helm.html) regarding mergeOverwrite issue

Basically a line as the following:
```
{{- mergeOverwrite .Values.config $lowDataDefault | toYaml | nindent 4 -}}
```

Not only prints the overwritten value, but it modifies as well the value of the config. From that point on ".Values.config" changes.

This issue becomes more tricky whenever you render twice the same template (for example in order to compute the hash). In this case the first execution is done with a value, the second one with different ones. In case you have an `if` checking that variable, the result of the execution could be completely different.

A possible solution is to perform a `deepCopy` of the variable. Notice that merely creating a variable and assign to it a value is NOT sufficient

Example of fix https://github.com/newrelic/nri-prometheus/pull/312. @kang-makes wanted as well to create a style guide to solve the issue in a better way

**Comment by kang-makes** [comment]
Charts reviewed that could have this issue:
- [ ] newrelic-infrastructure
- [ ] nri-prometheus
- [ ] nri-metadata-injection
- [ ] newrelic-k8s-metrics-adapter
- [ ] kube-state-metrics
- [ ] nri-kube-events
- [ ] newrelic-infra-operator
