### ISSUE TITLE
[nri-bundle] kube-state-metrics doesn't support K8s 1.22

### ISSUE THREAD

**Issue by simonkey007** [newrelic/helm-charts#860]
**Bug description**
kube-state-metrics doesn't support K8s 1.22

**Version of Helm and Kubernetes**

I'm running Kubernetes in version `1.22` with Helm in version 3.

**Which chart?**

nri-bundle in version `4.6.1`

**What happened?**

I'm getting the following errors from `kube-state-metrics` pod:
```
E0622 09:47:25.036925       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1beta1.CertificateSigningRequest: the server could not find the requested resource
E0622 09:47:25.061967       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1beta1.Ingress: the server could not find the requested resource (get ingresses.extensions)
```
Currently nri-bundle deploys `kube-state-metrics` helm chart in version [2.13.2](https://github.com/newrelic/helm-charts/blob/master/charts/nri-bundle/Chart.yaml#L44) what corresponds to kube-state-metrics app in version [1.9.8](https://github.com/prometheus-community/helm-charts/blob/kube-state-metrics-2.13.2/charts/kube-state-metrics/Chart.yaml#L10)

Version `1.9.8` supports Kubernetes up to version [1.16](https://github.com/kubernetes/kube-state-metrics/blob/v1.9.8/README.md#compatibility-matrix)

**What you expected to happen?**

kube-state-metrics should support K8s 1.22

**How to reproduce it?**

Deploy nri-bundle Helm chart on Kubernetes 1.22 and check logs from `kube-state-metrics` pod

**Anything else we need to know?**

I suggest to deploy `kube-state-metrics` in version [v2.2.0](https://github.com/kubernetes/kube-state-metrics/blob/v2.2.0/README.md#compatibility-matrix) which supports Kubernetes from 1.18 to 1.22

This means we should use `kube-state-metrics` helm chart in version [4.0.1](https://github.com/prometheus-community/helm-charts/blob/kube-state-metrics-4.0.1/charts/kube-state-metrics/Chart.yaml#L10) which includes the application version mentioned above.

**Comment by caseyclarkjamf** [comment]
Hey @alvarocabanas,

When you say "We don't support KSM 2.x.x yet", does that mean it's not supported in the Helm Chart or does that mean the New Relic integration itself won't work we provide our own kube-state-metrics version v2.2.0 and point New Relic at that instance?
