### ISSUE TITLE
[nri-bundle] Changes and release notes

### ISSUE THREAD

**Issue by jayntguru** [newrelic/helm-charts#864]
Howdy folks, just a request here.

When new versions are released there are often no change notes ("what's changed") associated.

[Just take a look here. It's here for some, but not all. ](https://github.com/newrelic/helm-charts/releases)

This makes it really difficult to determine is a fix or feature we need is included.

Can these be consistently added going forward?

Thank you.

**Comment by davidgit** [comment]
We appreciate you taking the time to bring this to our attention. 

We are currently adding automated release notes for all the New Relic integration repositories. However, this repository won't be taken into account during this first iteration but it will updated later.

If you have any further questions or comments about this, please let us know by replying to this issue.
