### ISSUE TITLE
[nri-bundle/Kube State Metrics] Possibility of upgrading the Kube State Metrics version

### ISSUE THREAD

**Issue by adamyaziji** [newrelic/helm-charts#889]
### Describe *in detail* the feature/behavior/change you'd like to see.

I would like to be able to use the latest version of Kube State Metrics (KSM). At the moment it looks like its using:
```
Chart version: 2.13.3
Image version: 1.9.8
```
but this seem to be [vastly outdated (23rd Feb 2021)](https://github.com/kubernetes/kube-state-metrics/releases/tag/v1.9.8).
Is there any chance you can allow us to use the [latest version](https://github.com/prometheus-community/helm-charts/releases/tag/kube-state-metrics-4.13.0) or at least a more updated version? Current versions:
```
Chart version: 4.13.0
Image version: 2.5.0
```

I see that the description provided in the README [here](https://github.com/newrelic/helm-charts/blob/e52bf6ca0719bcaf604a3ec1c4014d187a981500/charts/nri-bundle/README.md?plain=1#L138) shows that we can supply our own KSM but we are still limited to version <=2.

### **Is your feature request related to a problem? Please describe.**

Can't use the latest KSM version and is outdated by nearly 18 months.

### **Describe the solution you'd like**

The ability to move over to the new helm charts which are maintained by [prometheus-community](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics)

### **Describe alternatives you've considered**

Providing my own KSM deployment, however apparently we are still limited to only using version <=2 which would still be very outdated.

### **Additional context**

If there is another solution or a workaround then I am all ears!

Thanks, guys!

**Comment by adamyaziji** [comment]
Also as an FYI, the main reason I want to upgrade to later version is due to one of the metrics having very high cardinality as mentioned by someone else in this issue: https://github.com/kubernetes/kube-state-metrics/issues/1321. This is causing very large data ingestion. 

This is the release with the fix in: https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.0.0-rc.0

I know this release is technically within ```<=2.0``` so it might be okay but I'm not sure if ```<=2.0``` is a typo and its actually meant to be ```<2.0```. If this release is in fact compatible with new relic infrastructure agent then I am happy to provide my own KSM deployment with this version. 

But I strongly believe that it would be a nicer experience to keep this within new relic and have the ability to have latest KSM release within the nri-bundle chart.

**Comment by meyerkev** [comment]
I'll also add that we're now running EKS k8s version 1.22 which no longer contains Ingress version v1beta1.  So we either need to revert everything to v1.21 or we need to get a patch for this and 1.9.x is old enough I'd prefer the patch.  

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

**Comment by walkamongus** [comment]
I just ran into an issue that could also benefit from newer `kube-state-metrics` chart versions as well. Chart version `4.5.0` adds a `namespacesDenylist` value for filtering out namespaces. This would be useful for optimizing data ingest in certain cases.

**Comment by psyfox** [comment]
Advise: Upgrading it can result in loss of HPA metrics due to this:

`All metrics with a prefix of kube_hpa_* were renamed to kube_horizontalpodautoscaler_*.`

https://kubernetes.io/blog/2021/04/13/kube-state-metrics-v-2-0/

So We still need NR's attention to this issue

**Comment by psyfox** [comment]
Looks like bundle v5.0.0 fixed this: https://github.com/newrelic/helm-charts/commit/943d2f395d4206f9306eb8b0428c38392d2a6447#diff-5b5b4e84ee5774a52ded11c1661f97bc829a6a562d2e5c20eb28b77162893340

@adamyaziji Already tried this version?
