### ISSUE TITLE
newrelic-bundle preinstall job pod fails on mixed node cluster

### ISSUE THREAD

**Issue by lftroyer** [newrelic/helm-charts#932]
Chart deployment attempts newrelic-bundle-nri-metadata-injection-admission-create job and fails on mixed node cluster.

Attempting deployment of newrelic-bundle chart on an EKS cluster with both Linux and Windows nodes using:
--set global.nodeSelector."kubernetes\.io/os"=linux.  (also tried just node.Selector."kubernetes\.io/os"=linux).
The installation fails with "Error: failed pre-install: timed out waiting for the condition".  This is because the newrelic-bundle-nri-metadata-injection-admission-create job pod is getting scheduled on a Windows node and cannot mount the volumes.  We have tried manually editing the job and adding:
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: linux
but it is not honored.

Helm 3.6.3, Kubernetes on EKS 1.21
newrelic-bundle chart version 4.8.4

**What happened?**

Preinstall job pod fails.

**What you expected to happen?**

Preinstall job pod should respect node.Selector and schedule on a Linux node.

**How to reproduce it?**

Run helm upgrade --install newrelic-bundle newrelic/nri-bundle --set global.nodeSelector."kubernetes\.io/os"=linux on a mixed node kubernetes cluster with other required options.

**Comment by marcsanmi** [comment]
Hi @lftroyer,

We shipped a new release of the `nri-bundle`, specifically `v4.8.11`, with the new charts now honouring the `nodeSelector` labels set in `Job` objects.

Thanks for reporting it.
