### ISSUE TITLE
[newrelic-bundle-kube-state-metrics] doesn't deploy node.Selector setting

### ISSUE THREAD

**Issue by lftroyer** [newrelic/helm-charts#969]
** Chart deployment newrelic-kube-state-metrics fails on mixed node cluster. **

Follow up from closed issue #932, newrelic-bundle now deploys, but the newrelic-bundle-kube-state-metrics pod will not start if scheduled on a windows node

We were able to manually edit the newrelic-kube-state-metrics and add node.selector to get the pod scheduled.

Attempting deployment of newrelic-bundle chart on an EKS cluster with both Linux and Windows nodes using:
--set global.nodeSelector."kubernetes.io/os"=linux. 

Helm 3.6.3, Kubernetes on EKS 1.21
newrelic-bundle chart version 4.8.4

What happened?

newrelic-kube-state-metrics pod fails.

What you expected to happen?

newrelic-kube-state-metrics should deploy node.Selector setting and schedule on a Linux node.

How to reproduce it?

Run helm upgrade --install newrelic-bundle newrelic/nri-bundle --set global.nodeSelector."kubernetes.io/os"=linux on a mixed node kubernetes cluster with other required options.

**Comment by lftroyer** [comment]
Deployed chart version is currently 4.8.11

**Comment by davidgit** [comment]
Hi @lftroyer,

We understand this is not actually a bug. We are going to take this into account whenever we support KSM v2 which is in New Relic's roadmap.

**Comment by lftroyer** [comment]
Ok, but the pod will not start without manually editing the deployment.

**Comment by kang-makes** [comment]
What David meant to say is that that chart is not owned by us and you have to manually set the `nodeSelector` to it as it does not honor the `common-library`.

The values below the [`kube-state-metrics`](https://github.com/newrelic/helm-charts/blob/f7a8517/charts/nri-bundle/values.yaml#L13) are passed to the `kube-state-metrics` chart that you can inspect [here](https://github.com/kubernetes/kube-state-metrics/blob/kube-state-metrics-helm-chart-2.13.3/charts/kube-state-metrics/values.yaml#L93).

You should be able to tweak it until you set `nodeSelector` properly.
